### ISSUE TITLE
Disconnect between match probability formula in SeqPurge paper and code

### ISSUE THREAD

**Issue by jdidion** [imgag/ngs-bits#1]
I was just comparing the match probability formula from your paper:

![image](https://cloud.githubusercontent.com/assets/125854/17535540/276ca7a8-5e5d-11e6-8284-d8b10d27ebd0.png)

to the code:

```
double p = 0.0;
for (int i=matches; i<=count; ++i)
{
	double q = std::pow(0.75, count-i) * std::pow(0.25, i) * fak(count) / fak(matches) / fak(mismatches);
	p += q;
}
```

and they don't seem to match up. I thought I might just be stupid and didn't recognize a shortcut, so I just calculated a simple example by hand (and reimplemented your formula in python). In this case, n = 5 and k = 3:

```
# calculation based on published formula
i3 = (120 / (6 * 2)) * (0.25**3) * (0.75**2)
i4 = (120 / (24 * 1)) * (0.25**4) * (0.75**1)
i5 = (120 / (120 * 1)) * (0.25**5) * (0.75**0)
i3+i4+i5 # => 0.103515625
```
```
# calculation based on code
p = 0.0
import math
for i in [3,4,5]:
    q = (0.75 ** (5-i)) * (0.25 ** i) * math.factorial(5) / math.factorial(3) / math.factorial(2)
    p += q
print(p) # => 0.126953125
```

Am I making a stupid mistake here? Or is this a bug? And if so, what implications does that have for the results in your paper?

**Comment by marc-sturm** [comment]
Dear John,

thanks for tracking down this bug.
I checked and found that the calcualted probabilities with a high number of matches are hardly affected. The example below shows the original and fixed probabilities for n=100 and k=0...100:
> 0 4.8108e-13 1
> 1 1.6036e-11 1
> 2 2.64594e-10 1
> 3 2.88114e-09 1
> 4 2.32892e-08 1
> 5 1.49051e-07 1
> 6 7.86657e-07 1
> 7 3.52123e-06 0.999999
> 8 1.36448e-05 0.999997
> 9 4.64932e-05 0.999988
> 10 0.000141029 0.999957
> 11 0.000384626 0.999863
> 12 0.000950881 0.999606
> 13 0.00214558 0.998973
> 14 0.00444441 0.997542
> 15 0.00849376 0.994579
> 16 0.015041 0.988917
> 17 0.0247735 0.978889
> 18 0.0380777 0.962374
> 19 0.0547785 0.936989
> 20 0.073951 0.90047
> 21 0.093906 0.851169
> 22 0.112403 0.788565
> 23 0.127064 0.71363
> 24 0.135888 0.628921
> 25 0.1377 0.538329
> 26 0.132403 0.446529
> 27 0.120961 0.35826
> 28 0.105121 0.277619
> 29 0.0869967 0.207539
> 30 0.0686307 0.149541
> 31 0.0516575 0.103787
> 32 0.0371288 0.0693489
> 33 0.0255026 0.0445963
> 34 0.0167517 0.0275946
> 35 0.0105297 0.0164267
> 36 0.0063373 0.00940697
> 37 0.00365394 0.0051821
> 38 0.00201928 0.00274614
> 39 0.00107005 0.00139996
> 40 0.00054394 0.000686592
> 41 0.000265337 0.000323965
> 42 0.000124245 0.000147074
> 43 5.58621e-05 6.42443e-05
> 44 2.41223e-05 2.70029e-05
> 45 1.00063e-05 1.09214e-05
> 46 3.98801e-06 4.2506e-06
> 47 1.52732e-06 1.59193e-06
> 48 5.62139e-07 5.73712e-07
> 49 1.98852e-07 1.98953e-07
> 50 6.76097e-08 6.6385e-08
> 51 2.20947e-08 2.13119e-08
> 52 6.93999e-09 6.58214e-09
> 53 2.09509e-09 1.95548e-09
> 54 6.07835e-10 5.58755e-10
> 55 1.69457e-10 1.53531e-10
> 56 4.53903e-11 4.05599e-11
> 57 1.16794e-11 1.02997e-11
> 58 2.88628e-12 2.51346e-12
> 59 6.8488e-13 5.8927e-13
> 60 1.56001e-13 1.32683e-13
> 61 3.40985e-14 2.86831e-14
> 62 7.14968e-15 5.9508e-15
> 63 1.4375e-15 1.18435e-15
> 64 2.77019e-16 2.26015e-16
> 65 5.11419e-17 4.13357e-17
> 66 9.04023e-18 7.24107e-18
> 67 1.52919e-18 1.21424e-18
> 68 2.4737e-19 1.94782e-19
> 69 3.82407e-20 2.98687e-20
> 70 5.64506e-21 4.37494e-21
> 71 7.95078e-22 6.11565e-22
> 72 1.06747e-22 8.15132e-23
> 73 1.3648e-23 1.03487e-23
> 74 1.65989e-24 1.2501e-24
> 75 1.91809e-25 1.43509e-25
> 76 2.10317e-26 1.56356e-26
> 77 2.18511e-27 1.61449e-27
> 78 2.14776e-28 1.57742e-28
> 79 1.9937e-29 1.4558e-29
> 80 1.74449e-30 1.26668e-30
> 81 1.43579e-31 1.03685e-31
> 82 1.10895e-32 7.96587e-33
> 83 8.01648e-34 5.72886e-34
> 84 5.40795e-35 3.84541e-35
> 85 3.39322e-36 2.40109e-36
> 86 1.9728e-37 1.38939e-37
> 87 1.05821e-38 7.41839e-39
> 88 5.21087e-40 3.63665e-40
> 89 2.34196e-41 1.62733e-41
> 90 9.54129e-43 6.60172e-43
> 91 3.49494e-44 2.40821e-44
> 92 1.13962e-45 7.8212e-46
> 93 3.26738e-47 2.23382e-47
> 94 8.10805e-49 5.52369e-49
> 95 1.7054e-50 1.15853e-50
> 96 2.95262e-52 2.004e-52
> 97 4.02505e-54 2.74482e-54
> 98 4.00451e-56 2.79108e-56
> 99 2.48921e-58 1.87313e-58
> 100 6.22302e-61 6.22302e-61

Due to the the match percentage cutoff (80% is default), probabilities for low match rates are not calculated. I guess this is why I did not notice the bug earlier.

The unit tests for SeqPurge did not detect any change after the fix. That's good.

We'll know more once the re-calculation of the paper benchmarks are complete. They are just running...

**Comment by marc-sturm** [comment]
Dear John,

the re-calculation of the paper benchmark showed that there is no change when the base match percentage is high. This is consistent with the unchanged unit tests.

When the base match percentage is low, the correct formula gives better results than the wrong formula. For reasonable parameter choices the improvement are however not really significant.

Thus, I close the issue now.
Thanks again for finding the bug. If you have any further questions, don't hesitate to contect me.

Best,
  Marc

**Comment by jdidion** [comment]
Thanks Marc. Good to know that there's not much effect, and that the correct formula is better than the wrong formula :)
