### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by Martaprf** [imgag/ngs-bits#103]
Hi, I'm getting the error below in bold when running make build_tools_release:
rm -rf build-tools-Linux-Release;
mkdir -p build-tools-Linux-Release;
cd build-tools-Linux-Release; \
        qmake ../src/tools.pro "CONFIG-=debug" "CONFIG+=release" "DEFINES+=QT_NO_DEBUG_OUTPUT"; \
        make -j5;
Info: creating stash file /home/mferreira/programs/ngs-bits/build-tools-Linux-Release/.qmake.stash
make[1]: Entering directory '/home/mferreira/programs/ngs-bits/build-tools-Linux-Release'
cd cppCORE/ && ( test -e Makefile || /home/mferreira/anaconda3/bin/qmake -o Makefile /home/mferreira/programs/ngs-bits/src/cppCORE/cppCORE.pro CONFIG-=debug CONFIG+=release DEFINES+=QT_NO_DEBUG_OUTPUT ) && make -f Makefile
cd NGSDAddVariantsSomatic/ && ( test -e Makefile || /home/mferreira/anaconda3/bin/qmake -o Makefile /home/mferreira/programs/ngs-bits/src/NGSDAddVariantsSomatic/NGSDAddVariantsSomatic.pro CONFIG-=debug CONFIG+=release DEFINES+=QT_NO_DEBUG_OUTPUT ) && make -f Makefile
make[2]: Entering directory '/home/mferreira/programs/ngs-bits/build-tools-Linux-Release/cppCORE'
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o Exceptions.o ../../src/cppCORE/Exceptions.cpp
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o Settings.o ../../src/cppCORE/Settings.cpp
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o Log.o ../../src/cppCORE/Log.cpp
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o Helper.o ../../src/cppCORE/Helper.cpp
make[2]: Entering directory '/home/mferreira/programs/ngs-bits/build-tools-Linux-Release/NGSDAddVariantsSomatic'
g++ -pipe -O3 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../../anaconda3/mkspecs/features/data/dummy.cpp
/home/mferreira/anaconda3/bin/moc -DQT_NO_DEBUG_OUTPUT -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_CORE_LIB --include ./moc_predefs.h -I/home/mferreira/anaconda3/mkspecs/linux-g++ -I/home/mferreira/programs/ngs-bits/src/NGSDAddVariantsSomatic -I/home/mferreira/programs/ngs-bits/src/cppCORE -I/home/mferreira/programs/ngs-bits/src/cppXML -I/home/mferreira/programs/ngs-bits/src/cppNGS -I/home/mferreira/programs/ngs-bits/htslib/include -I/home/mferreira/programs/ngs-bits/src/cppNGSD -I/home/mferreira/anaconda3/include/qt -I/home/mferreira/anaconda3/include/qt/QtSql -I/home/mferreira/anaconda3/include/qt/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../../src/NGSDAddVariantsSomatic/main.cpp -o main.moc
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_CORE_LIB -I../../src/NGSDAddVariantsSomatic -I. -I../../src/cppCORE -I../../src/cppXML -I../../src/cppNGS -I../../htslib/include -I../../src/cppNGSD -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtSql -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o main.o ../../src/NGSDAddVariantsSomatic/main.cpp
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o BasicStatistics.o ../../src/cppCORE/BasicStatistics.cpp
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o FileWatcher.o ../../src/cppCORE/FileWatcher.cpp
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o LinePlot.o ../../src/cppCORE/LinePlot.cpp
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o WorkerBase.o ../../src/cppCORE/WorkerBase.cpp
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o ToolBase.o ../../src/cppCORE/ToolBase.cpp
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o TSVFileStream.o ../../src/cppCORE/TSVFileStream.cpp
g++ -Wl,-rpath,'$ORIGIN' -Wl,-O1 -Wl,-rpath,/home/mferreira/anaconda3/lib -o ../../bin/NGSDAddVariantsSomatic main.o   -L/home/mferreira/programs/ngs-bits/src/../bin -lcppCORE -lcppXML -lcppNGS -L/home/mferreira/programs/ngs-bits/src/../htslib/lib/ -lhts -lz -L/home/mferreira/programs/ngs-bits/src/NGSDAddVariantsSomatic/../bin -lcppNGSD -L/home/mferreira/anaconda3/lib -lQt5Sql -lQt5Core -lpthread
**/usr/bin/ld: cannot find -lcppCORE
/usr/bin/ld: cannot find -lcppXML
/usr/bin/ld: cannot find -lcppNGS
/usr/bin/ld: cannot find -lcppNGSD
collect2: error: ld returned 1 exit status
Makefile:241: recipe for target '../../bin/NGSDAddVariantsSomatic' failed
make[2]: *** [../../bin/NGSDAddVariantsSomatic] Error 1
make[2]: Leaving directory '/home/mferreira/programs/ngs-bits/build-tools-Linux-Release/NGSDAddVariantsSomatic'
Makefile:2373: recipe for target 'sub-NGSDAddVariantsSomatic-make_first' failed
make[1]: *** [sub-NGSDAddVariantsSomatic-make_first] Error 2**
make[1]: *** Waiting for unfinished jobs....
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o ScatterPlot.o ../../src/cppCORE/ScatterPlot.cpp
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o BarPlot.o ../../src/cppCORE/BarPlot.cpp
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o Histogram.o ../../src/cppCORE/Histogram.cpp
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o SimpleCrypt.o ../../src/cppCORE/SimpleCrypt.cpp
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o TsvFile.o ../../src/cppCORE/TsvFile.cpp
g++ -pipe -O3 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../../anaconda3/mkspecs/features/data/dummy.cpp
/home/mferreira/anaconda3/bin/moc -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB --include ./moc_predefs.h -I/home/mferreira/anaconda3/mkspecs/linux-g++ -I/home/mferreira/programs/ngs-bits/src/cppCORE -I/home/mferreira/anaconda3/include/qt -I/home/mferreira/anaconda3/include/qt/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../../src/cppCORE/ToolBase.h -o moc_ToolBase.cpp
/home/mferreira/anaconda3/bin/moc -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB --include ./moc_predefs.h -I/home/mferreira/anaconda3/mkspecs/linux-g++ -I/home/mferreira/programs/ngs-bits/src/cppCORE -I/home/mferreira/anaconda3/include/qt -I/home/mferreira/anaconda3/include/qt/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../../src/cppCORE/FileWatcher.h -o moc_FileWatcher.cpp
/home/mferreira/anaconda3/bin/moc -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB --include ./moc_predefs.h -I/home/mferreira/anaconda3/mkspecs/linux-g++ -I/home/mferreira/programs/ngs-bits/src/cppCORE -I/home/mferreira/anaconda3/include/qt -I/home/mferreira/anaconda3/include/qt/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../../src/cppCORE/WorkerBase.h -o moc_WorkerBase.cpp
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o moc_ToolBase.o moc_ToolBase.cpp
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o moc_FileWatcher.o moc_FileWatcher.cpp
g++ -c -pipe -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -DCPPCORE_VERSION=\"2020_09\" -DCRYPT_KEY=\"\" -DQT_NO_DEBUG -DQT_CORE_LIB -I../../src/cppCORE -I. -I../../../../anaconda3/include/qt -I../../../../anaconda3/include/qt/QtCore -I. -I../../../../anaconda3/mkspecs/linux-g++ -o moc_WorkerBase.o moc_WorkerBase.cpp
rm -f libcppCORE.so.1.0.0 libcppCORE.so libcppCORE.so.1 libcppCORE.so.1.0
g++ -Wl,-O1 -Wl,-rpath,/home/mferreira/anaconda3/lib -shared -Wl,-soname,libcppCORE.so.1 -o libcppCORE.so.1.0.0 Exceptions.o Settings.o Log.o Helper.o BasicStatistics.o FileWatcher.o LinePlot.o WorkerBase.o ToolBase.o TSVFileStream.o ScatterPlot.o BarPlot.o Histogram.o SimpleCrypt.o TsvFile.o moc_ToolBase.o moc_FileWatcher.o moc_WorkerBase.o  -L/home/mferreira/anaconda3/lib -lQt5Core -lpthread
ln -s libcppCORE.so.1.0.0 libcppCORE.so
ln -s libcppCORE.so.1.0.0 libcppCORE.so.1
ln -s libcppCORE.so.1.0.0 libcppCORE.so.1.0
rm -f ../../bin/libcppCORE.so.1.0.0
mv -f libcppCORE.so.1.0.0  ../../bin/
rm -f ../../bin/libcppCORE.so
rm -f ../../bin/libcppCORE.so.1
rm -f ../../bin/libcppCORE.so.1.0
mv -f libcppCORE.so ../../bin/
mv -f libcppCORE.so.1 ../../bin/
mv -f libcppCORE.so.1.0 ../../bin/
**make[2]: Leaving directory '/home/mferreira/programs/ngs-bits/build-tools-Linux-Release/cppCORE'
make[1]: Leaving directory '/home/mferreira/programs/ngs-bits/build-tools-Linux-Release'
Makefile:49: recipe for target 'build_tools_release' failed
make: *** [build_tools_release] Error 2**

Someone can help me why I am getting this error?

thanks

**Comment by marc-sturm** [comment]
Hi,

is this the master, or which version have you cloned?

Please try if calling 'make build_libs_release' before 'make build_tools_release' fixes the problem.

Best,
  Marc

**Comment by Martaprf** [comment]
Hi Marc,

I have cloned the last version, but you help solve my problem.

Thanks a lot!
