### ISSUE TITLE
Error:Only strelka and freebayes are currently supported

### ISSUE THREAD

**Issue by zyywmy** [imgag/ngs-bits#11]
I tried to run SomaticQC but it showed "Only strelka and freebayes are currently supported".
Does the software support Mutect result VCF files?
Thanks,

**Comment by marc-sturm** [comment]
Sorry, but only strelka and freebayes are currently supported.

**Comment by zmiimz** [comment]
any changes or plans to solve this issue?

**Comment by marc-sturm** [comment]
We can update the tool.
Should not be too hard.

Do you perhaps have example VCFs you can share?

**Comment by marc-sturm** [comment]
@leonschuetz Ist das fertig?

**Comment by leonschuetz** [comment]
support implemented in commit 40b53697afa476c030f63d13d3a12abec90b49b3
