### ISSUE TITLE
filelist format

### ISSUE THREAD

**Issue by foreverwander** [imgag/ngs-bits#110]
Apologies as this is an naive question, and I havn't explored the entire package to find a hint elsewhere...

I'm looking to run SampleGender on my list of ~60 BAMs

The help says:
`-in <filelist>      Input BAM file(s).`

I'm just wondering what the format should be if one wants to input more than one BAMs. So far putting the path to one BAM has worked for me, but I cannot figure out how to input more BAMs. I have tried comma separation, space separation, and inputting a file that has the path to one BAM on each line, and that lead to a segmentation fault.

Thank you.

**Comment by marc-sturm** [comment]
Hi,


the BAM files need to be space-separated. the 'in' parameter simply takes a list of files.


Best,

  Marc


________________________________
Von: Lydia Y. Liu <notifications@github.com>
Gesendet: Dienstag, 8. Dezember 2020 22:04
An: imgag/ngs-bits
Cc: Subscribed
Betreff: [imgag/ngs-bits] filelist format (#110)


Apologies as this is an naive question, and I havn't explored the entire package to find a hint elsewhere...

I'm looking to run SampleGender on my list of ~60 BAMs

The help says:
-in <filelist> Input BAM file(s).

I'm just wondering what the format should be if one wants to input more than one BAMs. So far putting the path to one BAM has worked for me, but I cannot figure out how to input more BAMs. I have tried comma separation, space separation, and inputting a file that has the path to one BAM on each line, and that lead to a segmentation fault.

Thank you.

**Comment by foreverwander** [comment]
Great that clarifies things. Can you please add that to the documentation? Most tools I've seen use comma separation
