### ISSUE TITLE
Compile Error - undefined references to BamTools functions

### ISSUE THREAD

**Issue by epon93** [imgag/ngs-bits#12]
Hello,

First, I am using a version of qt greater than 5.5. Here is the output of `qmake -v`:
> QMake version 3.0
> Using Qt version 5.6.1 in /usr/lib64

I am getting the following error during the process of running `make build_tools_release`: 

> g++ -Wl,-rpath,'$ORIGIN' -Wl,-O1 -o ../../bin/SamplesNGSD main.o   -Lngs-bits/src/../bin -lcppCORE -lcppXML -lcppNGS -Lngs-bits/src/../bamtools/lib/ -lbamtools -lz -Lngs-bits/src/SamplesNGSD/../bin -lcppNGSD -lQt5Sql -lQt5Core -lpthread 
> ngs-bits/src/../bin/libcppNGS.so: undefined reference to \`BamTools::BamReader::GetReferenceID(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
> ngs-bits/src/../bin/libcppNGS.so: undefined reference to \`BamTools::BamReader::Open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> ngs-bits/src/../bin/libcppNGS.so: undefined reference to \`BamTools::BamAlignment::IsValidSize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
> ngs-bits/src/../bin/libcppNGS.so: undefined reference to \`BamTools::BamAlignment::FindTag(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char*&, unsigned int const&, unsigned int&) const'
> ngs-bits/src/../bin/libcppNGS.so: undefined reference to \`BamTools::BamReader::OpenIndex(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> ngs-bits/src/../bin/libcppNGS.so: undefined reference to \`_ZNK8BamTools9BamReader14GetErrorStringB5cxx11Ev'
> ngs-bits/src/../bin/libcppNGS.so: undefined reference to \`_ZNK8BamTools9BamReader11GetFilenameB5cxx11Ev'
> collect2: error: ld returned 1 exit status
> make[2]: *** [../../bin/SamplesNGSD] Error 1
> make[2]: Leaving directory \`ngs-bits/build-tools-Linux-Release/SamplesNGSD'
> make[1]: *** [sub-SamplesNGSD-make_first] Error 2
> make[1]: Leaving directory `ngs-bits/build-tools-Linux-Release'
> make: *** [build_tools_release] Error 2

Any idea what the problem could be?

**Comment by marc-sturm** [comment]
Hi,

have you executed "make build_3rdparty" before building ngs-bits?
It is supposed to build the bamtools library, which might be missing in
your case.

Best,
  Marc

**Comment by e-p-o-n** [comment]
Yes, I did build_3rdparty first which seemed to have completed successfully.

**Comment by marc-sturm** [comment]
Can you please post the output of
> ldd ngs-bits/bamtools/lib/libbamtools.so
That's the library that should contain the missing symbols.

Best,
 Marc

**Comment by e-p-o-n** [comment]
> 	linux-vdso.so.1 =>  (0x00002aaaaaaab000)
> 	libz.so.1 => /lib64/libz.so.1 (0x00002aaaaad49000)
> 	libstdc++.so.6 => /[redacted]/gcc/gcc_6_1_0/lib64/libstdc++.so.6 (0x00002aaaaaf60000)
> 	libm.so.6 => /lib64/libm.so.6 (0x00002aaaab2f5000)
> 	libgcc_s.so.1 => /[redacted]/gcc/gcc_6_1_0/lib64/libgcc_s.so.1 (0x00002aaaab579000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00002aaaab790000)
> 	/lib64/ld-linux-x86-64.so.2 (0x0000003f96a00000)

**Comment by marc-sturm** [comment]
Hmm, everything looks fine. I'm a bit puzzled.

Can you also post the output of
> g++ -- version
and
> cat /etc/issue

I think I will have to reproduce the problem in a virtual machine using the
same Linux etc.

Thanks,
  Marc

**Comment by e-p-o-n** [comment]
g++ (GCC) 6.1.0

CentOS release 6.9 (Final)

**Comment by marc-sturm** [comment]
thanks, I will try to repoduce it monday or tuesday.

Best,
  Marc

**Comment by e-p-o-n** [comment]
Hmm, actually I have just tried with a different gcc version (4.8.4) and it looks like it finished properly. You may still want to test it for compatibility with the newer compiler version, but I think I'm set.

**Comment by marc-sturm** [comment]
Great, I leave the issue open for testing with gcc 6 though.
  - Marc

**Comment by Francesc-Muyas** [comment]
Hi Marc, 
I had a similar problem. 
make build_3rdparty seemed to work, but when I run make build_tools_release I got this output error:

rm -rf build-tools-Linux-Release;
mkdir -p build-tools-Linux-Release;
cd build-tools-Linux-Release; \
	qmake ../src/tools.pro "CONFIG-=debug" "CONFIG+=release" "DEFINES+=QT_NO_DEBUG_OUTPUT"; \
	make;
qmake[1]: Entering directory '/nfs/users2/so/fmuyas/programs/ngs-bits/build-tools-Linux-Release'
qmake[1]: Nothing to be done for '../src/tools.pro'.
qmake[1]: Leaving directory '/nfs/users2/so/fmuyas/programs/ngs-bits/build-tools-Linux-Release'
make[1]: Entering directory `/nfs/users2/so/fmuyas/programs/ngs-bits/build-tools-Linux-Release'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/nfs/users2/so/fmuyas/programs/ngs-bits/build-tools-Linux-Release'
make: *** [build_tools_release] Error 2

Why does it happen?

Cheers,

**Comment by marc-sturm** [comment]
Hi Francesc,

Did you install the dependencies as documented?

Can you please send me the output of "qmake --version" and "g++ --version".

Thanks,
  Marc

**Comment by Francesc-Muyas** [comment]
Hi Marc,
g++ : g++ (GCC) 4.9.3
qmake : GNU Make 4.0

I guess that the problems come with the qmake version right?

2017-10-09 16:08 GMT+02:00 Marc Sturm <notifications@github.com>:

**Comment by marc-sturm** [comment]
Hi Francesc,

that's the wrong qmake.
Please make sure Qt 5.5 or higher is installed and the QT qmake is in the
path.

Best,
  Marc

**Comment by rafalwoycicki** [comment]
I had the same problem with installation as epon93. It was not working with gcc-6.8.0 but with 5.3.0 it was OK.

**Comment by imgag** [comment]
GCC is now supported starting from this commit:
https://github.com/imgag/ngs-bits/commit/be24d7fe78afeef1bc9ed20d5eb44a93400672fa
