### ISSUE TITLE
error correction with targeted sequencing data

### ISSUE THREAD

**Issue by joonlee3** [imgag/ngs-bits#13]
I have run SeqPurge for my targeted sequencing data (17 gene panel).

With the error correction option, I received a core dump error message while there was no issue when I disabled the option.

I am just wondering if there is a way to resolve this issue. Please let me know.

**Comment by imgag** [comment]
can you share the data with me (at least the part the causes the core dump)?
As soon as I can reproduce the problem I can fix it.

Best,
  Marc

**Comment by imgag** [comment]
I guess that problem is solved or not relevant.
