### ISSUE TITLE
BedLow/HighCoverag > ScanLine

### ISSUE THREAD

**Issue by marc-sturm** [imgag/ngs-bits#138]

**Comment by marc-sturm** [comment]
- [ ] Test and benchmark scanline code in Tim's branch
- [ ] If fast enough, add low-coverage file for WGS (if the files are not too large to be handled by GSvar :)

**Comment by marc-sturm** [comment]
@tstohn Hallo Tim, mit welchem Use-Case hast du denn gebenchmarkt? Ich konnte bisher keine Beschleunigung feststellen...

**Comment by tstohn** [comment]
Hi Marc,
Hatte es auf mehreren Datensätzen getestet (ohne base quality), die 'relativ' groß waren, sodass die Laufzeit bei um die 30min lag.

**Comment by marc-sturm** [comment]
@tstohn danke, ich versuche es nochmal mit großen Genomen
