### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by wwood** [imgag/ngs-bits#14]
Hi, I'm getting this when running `make build_tools_release`, in a GNU Guix build environment:
```
cd cppCORE/ && ( test -e Makefile || /gnu/store/6fgh94phyq4239grgk8z7yjggldrvwbb-qt-5.6.2/bin/qmake /tmp/guix-build-ngs-bits-0-1.c39f1807.drv-0/source/src/cppCORE/cppCORE.pro CONFIG-=debug CONFIG+=release DEFINES+=QT_NO_DEBUG_OUTPUT -o Makefile ) && make -f Makefile 
Cannot find file: /tmp/guix-build-ngs-bits-0-1.c39f1807.drv-0/source/src/cppCORE/cppCORE.pro.
make[1]: *** [Makefile:117: sub-cppCORE-make_first] Error 2
make[1]: Leaving directory '/tmp/guix-build-ngs-bits-0-1.c39f1807.drv-0/source/build-tools-Linux-Release'
make: *** [Makefile:46: build_tools_release] Error 2
```
I get this when running `make build_3rdparty` beforehand or not. Is this a file missing from the repo or something?
ta, ben

**Comment by marc-sturm** [comment]
Hi,

the repository is complete and the Travis-CI-Tests pass.
There has to be some other error.

Which Lunix distribution, gcc version and Qt version are you using?

Best,
  Marc

**Comment by wwood** [comment]
It isn't complete when you don't git clone recursively and instead try to just try to clone the base and the bamtools - didn't realise there was further ones deeper in the tree. Sorry for the noise.
