### ISSUE TITLE
cppNGSD test crash in debug mode

### ISSUE THREAD

**Issue by axelgschwind** [imgag/ngs-bits#144]
When building ngs-bits mode in Debug mode, cppNGSD tests fail.

I could trace the problem to ChromosomalIndex<T>::matchingIndices where I see that the int "index" can have values higher than container_.count().
If i check the elements of "index_" I find values of -2147483648 first in pair indicating a possible problem with the size of these integers

However, if ngs-bits is built for release, all cppNGSD tests pass.

**Comment by axelgschwind** [comment]
The affected method is ChromosomalIndex::matchingIndices: The integer "index" has a higher value than container_.count().

**Comment by marc-sturm** [comment]
Fixed with 7e892501e927059c8d76b98bdf7c66578fb60d66

@axelgschwind Please test

**Comment by axelgschwind** [comment]
All test cases for cppNGSD work again. Thanks.
