### ISSUE TITLE
VcfAnnotateFromBed removes linebreaks from annotated line

### ISSUE THREAD

**Issue by dboceck** [imgag/ngs-bits#149]
When I try to annotate a VCF file with a BED file I am missing linebreaks in the annotated file.
This happens only in VCF files that contain no sample information so the INFO column is the last entry per variant line.

I added a zip folder with a small example to demonstrate the behaviour.

[example.zip](https://github.com/imgag/ngs-bits/files/6522599/example.zip)

**Comment by marc-sturm** [comment]
Fixed by 9c07d68d001e120415c7b84e7855c802e0723f7e
