### ISSUE TITLE
Qt Concurrent exception in SeqPurge

### ISSUE THREAD

**Issue by antonkulaga** [imgag/ngs-bits#16]
SeqPurge crashes with Qt Concurrent excecption:
```
Qt Concurrent has caught an exception thrown from a worker thread.
This is not supported, exceptions thrown in worker threads must be
caught before control returns to Qt Concurrent.
terminate called after throwing an instance of 'ProgrammingException'
```
Here are the commands that I type:
```
SeqPurge \
  -in1 /cromwell-executions/quality_de_novo/e859267e-e1dc-4cb7-8bda-53f2fe4c3055/call-trimming_seqpurge/inputs/pipelines/whales/graywhale/GWliver_S1_L001_R1_001.fastq.gz \
  -in2 /cromwell-executions/quality_de_novo/e859267e-e1dc-4cb7-8bda-53f2fe4c3055/call-trimming_seqpurge/inputs/pipelines/whales/graywhale/GWliver_S1_L001_R2_001.fastq.gz \
  -out1 GWliver_S1_L001_R1_001_trimmed.fastq.gz \
  -out2 GWliver_S1_L001_R2_001_trimmed.fastq.gz \
  -ec
```
I can upload the data for you to check. however it is several GBs

**Comment by marc-sturm** [comment]
if you can make the data available for me, I can check what goes wrong.

-Marc

**Comment by antonkulaga** [comment]
@marc-sturm looks like it crashes only when I have "-ec" (when I do not have it runs fine)
the files are
[1](https://drive.google.com/open?id=0B2mhFmX_zyibOFUxd2tZWlZWSDA) and [2](https://drive.google.com/open?id=0B2mhFmX_zyibYTFwQVV6YWJqZkE)
Let me know when you will download them, so I can remove them (they are quite large: 4 and 6 GBs).
I use docker  container virusx/seqpurge:32d9c85395a to run SeqPurge, but I do not think it is important because it is build with the recent version.

**Comment by marc-sturm** [comment]
Hi Anton,

yes, the '-ec' parameter algorithm has probably a bug. We don't use it very
often.

Still I would like to fix it.
I sent you requests to download the example files. The permissions were
missing...

Best,
  Marc

**Comment by antonkulaga** [comment]
@marc-sturm  I gave the permissions, if there are still issue with download - let me know

**Comment by marc-sturm** [comment]
Thanks, I downloaded the files. You can delete them.

Best,
  Marc

**Comment by imgag** [comment]
Hi Anton,

I just committed a fix for the crash:
https://github.com/imgag/ngs-bits/commit/426ed18a8928bff8754d3c9ceaf80786e8b44ee0

It works on your data for me now.
Can you please verify that it works for you as well.

Thanks,
  Marc
