### ISSUE TITLE
Seg fault when using -threads

### ISSUE THREAD

**Issue by mozack** [imgag/ngs-bits#17]
Hi, I'm getting Segmentation fault when using the -threads option.  Omitting -threads appears to be working.

Command:
SeqPurge -threads 4 -in1 n1.fastq.gz -in2 n2.fastq.gz -out1 n1.trim.fastq.gz -out2 n2.trim.fastq.gz -out3 singleton  > trim.log 2>&1

OS: Centos7

The test data is from here: https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/config/examples/cancer-giab-na12878-na24385-getdata.sh

From gdb where:
Core was generated by `/datastore/nextgenout4/seqware-analysis/lmose/software/seqpurge/ngs-bits/bin/Se'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fda01354b43 in deflate_fast () from /usr/lib64/libz.so.1
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 elfutils-libelf-0.166-2.el7.x86_64 elfutils-libs-0.166-2.el7.x86_64 expat-2.1.0-10.el7_3.x86_64 glib2-2.46.2-4.el7.x86_64 glibc-2.17-157.el7_3.5.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.14.1-27.el7_3.x86_64 libX11-1.6.5-1.el7.x86_64 libXau-1.0.8-2.1.el7.x86_64 libXdamage-1.1.4-4.1.el7.x86_64 libXext-1.3.3-3.el7.x86_64 libXfixes-5.0.3-1.el7.x86_64 libXxf86vm-1.1.4-1.el7.x86_64 libattr-2.4.46-12.el7.x86_64 libcap-2.22-8.el7.x86_64 libcom_err-1.42.9-9.el7.x86_64 libdrm-2.4.74-1.el7.x86_64 libgcc-4.8.5-11.el7.x86_64 libgcrypt-1.5.3-13.el7_3.1.x86_64 libgpg-error-1.12-3.el7.x86_64 libicu-50.1.2-15.el7.x86_64 libmodman-2.0.1-8.el7.x86_64 libpng-1.5.13-7.el7_2.x86_64 libproxy-0.4.11-10.el7.x86_64 libselinux-2.5-6.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64 libxcb-1.12-1.el7.x86_64 libxshmfence-1.2-1.el7.x86_64 mesa-libGL-17.0.1-6.20170307.el7.x86_64 mesa-libglapi-17.0.1-6.20170307.el7.x86_64 openssl-libs-1.0.2k-8.el7.x86_64 pcre-8.32-15.el7_2.1.x86_64 qt5-qtbase-5.6.2-1.el7.x86_64 qt5-qtbase-gui-5.6.2-1.el7.x86_64 qt5-qtxmlpatterns-5.6.2-1.el7.x86_64 systemd-libs-219-30.el7_3.9.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) where
#0  0x00007fda01354b43 in deflate_fast () from /usr/lib64/libz.so.1
#1  0x00007fda01355684 in deflate () from /usr/lib64/libz.so.1
#2  0x00007fda0135ee46 in gz_comp () from /usr/lib64/libz.so.1
#3  0x00007fda0135f10a in gzwrite () from /usr/lib64/libz.so.1
#4  0x00007fda0135f2e2 in gzputs () from /usr/lib64/libz.so.1
#5  0x00007fda01868fad in FastqOutfileStream::write (this=0x1df6780, entry=...)
    at ../../src/cppNGS/FastqFileStream.cpp:197
#6  0x000000000041045e in AnalysisWorker::run (this=0x1e75610) at ../../src/SeqPurge/AnalysisWorker.cpp:527
#7  0x00007fda00f6af4e in QThreadPoolThread::run() () from /usr/lib64/libQt5Core.so.5
#8  0x00007fda00f6e88d in QThreadPrivate::start(void*) () from /usr/lib64/libQt5Core.so.5
#9  0x00007fda00cb3dc5 in start_thread () from /usr/lib64/libpthread.so.0
#10 0x00007fda001c176d in clone () from /usr/lib64/libc.so.6

**Comment by imgag** [comment]
Sorry for the late response. I tried  to download the data several times, but the download is very slow and always aborts.

Since I suspected some muti-threading issue I checked the code and probably found the bug.
I just committed a fix (aa1b9906ceae2711b91ba3ae55b5ea7fe9bca3cd).

Can you please verify that this fixes the problem.

Best,
  Marc

**Comment by imgag** [comment]
I guess this is solved.
