### ISSUE TITLE
Error in SeqPurge summary info

### ISSUE THREAD

**Issue by mozack** [imgag/ngs-bits#18]
Looks like there may be a numeric overflow issue in the counting for large samples:

From the SeqPurge output:

Reads (forward + reverse): -1672475124

Reads trimmed by insert match: 10318654
Reads trimmed by adapter match: 4348594
Reads trimmed by quality: 1169503679
Reads trimmed by N stretches: 933927
Trimmed reads: 14667248 of -1672475124 (-0.88%)
Removed reads: 2070757 of -1672475124 (-0.12%)
Removed bases: -3.36%

Data downloaded from here:
https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/config/examples/cancer-giab-na12878-na24385-getdata.sh

The 24385-12878-30-200*.fastq.gz dataset has the issue.

**Comment by imgag** [comment]
thanks for the bug reports. I will look into it as soon as the data is downloaded. Looks like that download will take days though  - it's coming in at 500K/s...

  -Marc

**Comment by imgag** [comment]
Can you verify that the overflow no longer occurs with the latest version?

Best,
  Marc
