### ISSUE TITLE
Cannot compile tools

### ISSUE THREAD

**Issue by mocat2** [imgag/ngs-bits#2]
Hi,

I get this error when I run the make build_tools_release:

../../src/cppCORE/LinePlot.cpp:9:26: fatal error: QStandardPaths: No such file or directory
 #include <QStandardPaths>
                          ^
compilation terminated.
make[2]: *** [LinePlot.o] Error 1

**Comment by marc-sturm** [comment]
Hi,

can you please post the output of the command "qmake -v".
I suspect that Qt4 is used instead of Qt5, because QStandardPaths was added in Qt5. If so, you need to installiert 

Best, Marc

**Comment by marc-sturm** [comment]
Hi,

can you please post the output of the command "qmake -v".
I suspect that Qt4 is used instead of Qt5, because QStandardPaths was added in Qt5. If so, you need to install it.

Best, Marc

**Comment by mocat2** [comment]
Correct. I'll try to install qmake 5.

> qmake -v
QMake version 2.01a
Using Qt version 4.8.7 in /home/jroatkul/anaconda_ete/lib



---------------------------------
Jens Roat Kultima, Ph.D.

Computational Scientist
Janssen Human Microbiome Institute
Janssen Pharmaceuticals
255 Main Street, 10th Floor
Cambridge, MA 02142
---------------------------------
