### ISSUE TITLE
somatic report XML: add tables/images using base64-encoding.

### ISSUE THREAD

**Issue by marc-sturm** [imgag/ngs-bits#207]
The following blocks need to stored:
- summary (RTF, "Allgemeine genetische Characteristika")
- relevant_variants (RTF, "Potentiell relevante somatische Veränderungen")
- unclear_variants (RTF, "Varianten unklarer Onkogenität")
- cnvs (RTF, "Chromosomale Aberrationen")
- fusions (RTF, Fusionen)
- pharmaco_genetics (RTF, "Pharmakogenetisch relevante Polymorphismen")
- general_info (RTF, "Allgemeine Informationen" + "Qualitätsparameter")
- igv_screenshot (PNG, Klären was genau drauf soll!)
- mtb_summary (RTF, Klären was das ist!)

The XSD is already adapted in this branch:
https://github.com/imgag/ngs-bits/tree/somatic_report_xml_blocks

**Comment by axelgschwind** [comment]
I have merged the XSD file into my somatic RTF dev branch:
https://github.com/imgag/ngs-bits/tree/somatic_report_whole_exomes
and will continue development for the XML in this branch.

**Comment by axelgschwind** [comment]
I have added IGV snapshots to the RTF document including GSvar functionality in this branch. It also includes the snapshots for the XML document. I can therefore close this issue.
https://github.com/imgag/ngs-bits/tree/RtfImageParsing

It will be merged after I will have finished the novel somatic RNA report.
