### ISSUE TITLE
Reference genome FASTA unset in both command-line and settings.ini file!

### ISSUE THREAD

**Issue by Kiran936** [imgag/ngs-bits#230]
Hi, 

I am using below command to get MappingQC

MappingQC -in 20200148421.bam  -out QCML  -roi WES.bed

It is throwing below error 
Reference genome FASTA unset in both command-line and settings.ini file!

**Comment by marc-sturm** [comment]
You have to give the tool the reference genome FASTA file.

That you can do with the parameter "ref" or via the settings.ini file.

**Comment by Kiran936** [comment]
Thanks a lot,, Kindly make the user manual and example output,, that will help a lot,, i tried with only just BAM input which according to --help says mandatory ,, still it threw error

**Comment by Kiran936** [comment]
How to use the mlQC output file

**Comment by marc-sturm** [comment]
qcML is a QC format on XML basis.
Please have a look at the documentation: https://github.com/imgag/ngs-bits

If you want text based output, you can use the -txt flag:
https://github.com/imgag/ngs-bits/blob/master/doc/tools/MappingQC.md
