### ISSUE TITLE
Annotate pathways for driver genes in somatic report

### ISSUE THREAD

**Issue by leonschuetz** [imgag/ngs-bits#262]
- [x] model pathways in NGSD
- [x] import pathway data into NGSD
- [x] add pathway to relevant/potentially relevant variants table
- [x] add pathway table after general information
- [x] add table as RTF to somatic XML (for GenLab and MTB)

**Comment by marc-sturm** [comment]
Updated tables: 5e8151ef94cf9d275c607e1864db72c7c7172af8
