### ISSUE TITLE
RNA: ngs-bits RNA extension

### ISSUE THREAD

**Issue by leonschuetz** [imgag/ngs-bits#270]
- [x] import ~~transcripts~~/exons to NGSD ? (probably no live stats possible)
- [x] update DNA-RNA annotation to NGSD based data
- [x] replace python scripts for cohort annotation
- [x] add db functions for RNA report
- [x] add view for ~~transcript~~/exon-based

**Comment by jakobmatthes** [comment]
- [ ] return to file based data required?
      ![grafik](https://user-images.githubusercontent.com/1090078/173527298-d9bbd98d-909f-4b3b-b668-896efa3f2962.png)

**Comment by leonschuetz** [comment]
- [ ] detect exon skipping (DONE) and new exons
- [ ] monoallelic expression
- [ ] import exons into the NGSD

GSvar:   
- [ ] Add RNA info to report config of small variants, CNVs and SVs as enum: 'n/a', 'splicing effect validated by RNA dataset', 'not splicing effect found in RNA dataset', 'RNA dataset not usable' ?
- [ ] Summary of RNA in germline report: QC metrics (reads, correlation, ...)
- [ ]  Database with gene expression levels => determine genes (paste list or import from target region/subpanel) for which RNA expression can be used (in a certain tissue/processing system)
- [ ] Docu (GSvar markdown pages)
- [ ] Add view for exon expression

**Comment by jakobmatthes** [comment]
GSvar:

- [ ] show reference tissue expression column (if availabile in file, used in SomaticAndTreatment)

**Comment by leonschuetz** [comment]
- [ ] ExpressionGeneWidget: make quality selection in cohort determination adjustable

**Comment by leonschuetz** [comment]
- [ ] NGSDAnnotateRNA: add cohort strategy and column description in header
- [ ] ExpressionGeneWidget: add option to manually provide cohort

**Comment by leonschuetz** [comment]
- [ ] megSAP: add cohort table with expression for plots

**Comment by leonschuetz** [comment]
- [ ] add IGV integration to RNA exon/gene view
- [ ] add transcript info to RNA exon view
- [ ] FusionWidget: add IGV and arriba plots
