### ISSUE TITLE
OMIM link

### ISSUE THREAD

**Issue by ubuntolog** [imgag/ngs-bits#272]
There is a suggestion to improve the gene search on OMIM page:

`... wenn ich über die rechte Maustaste den Befehlt „open OMIM-page“ anklicke werde ich nicht direkt auf die Seite des Gens sondern auf eine Suchergebnisseite geleitet. Das finde ich auch nicht optimal. Besser wäre es, wenn man direkt auf die Genseite gelangt, so, als ob man aus einer SNV auf den OMIM-Gen code klickt. Vielleicht kann man den ja auch in der RE-Ergebnistabelle bei den Genen hinterlegen.`

**Comment by marc-sturm** [comment]
Not possible for RE table, because we do not have the MIM number for a direct link.
