### ISSUE TITLE
Cannot compile tools

### ISSUE THREAD

**Issue by tanaes** [imgag/ngs-bits#3]
Getting following error:

 ToolBase.o ../../src/cppCORE/ToolBase.cpp
../../src/cppCORE/ToolBase.cpp: In member function ‘void ToolBase::sortChangeLog()’:
../../src/cppCORE/ToolBase.cpp:566: error: expected primary-expression before ‘[’ token
../../src/cppCORE/ToolBase.cpp:566: error: expected primary-expression before ‘]’ token
../../src/cppCORE/ToolBase.cpp:566: error: expected primary-expression before ‘const’
../../src/cppCORE/ToolBase.cpp:566: error: expected primary-expression before ‘const’
make[2]: *** [ToolBase.o] Error 1
make[2]: Leaving directory `/home/jgsanders/git_sw/ngs-bits/build-tools-Linux-Release/cppCORE'
make[1]: *** [sub-cppCORE-make_first] Error 2
make[1]: Leaving directory `/home/jgsanders/git_sw/ngs-bits/build-tools-Linux-Release'
make: *** [build_tools_release] Error 2

**Comment by imgag** [comment]
I guess you are using a too old compiler, probabily g++.
What does `g++ --version` return? You need at least g++ 4.5, perhaps even higher.

Best,
  Marc

**Comment by tanaes** [comment]
So g++ indeed was pre 4.5; I upgraded to 4.8.5 and now get:

(goddammit)☕  brncl-03:ngs-bits $ make build_tools_release
rm -rf build-tools-Linux-Release;
mkdir -p build-tools-Linux-Release;
cd build-tools-Linux-Release; \
		qmake ../src/tools.pro "CONFIG-=debug" "CONFIG+=release" "DEFINES+=QT_NO_DEBUG_OUTPUT"; \
		make;
make[1]: Entering directory `/home/jgsanders/git_sw/ngs-bits/build-tools-Linux-Release'
cd cppCORE && qmake ../../src/cppCORE/cppCORE.pro "CONFIG-=debug" "CONFIG+=release" "DEFINES+=QT_NO_DEBUG_OUTPUT" -o Makefile
cd cppCORE && make -f Makefile
make[2]: Entering directory `/home/jgsanders/git_sw/ngs-bits/build-tools-Linux-Release/cppCORE'
g++ -c -pipe -Wall -W -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fno-strict-aliasing -O3 -fPIC  -DQT_NO_DEBUG_OUTPUT -DCPPCORE_LIBRARY -D"CPPCORE_VERSION=0.1-620-g4e306ef" -DQT_NO_DEBUG -DQT_SHARED -DQT_TABLET_SUPPORT -DQT_THREAD_SUPPORT -I/usr/lib64/qt-3.3/mkspecs/default -I../../src/cppCORE -I/usr/lib64/qt-3.3/include -I. -o Exceptions.o ../../src/cppCORE/Exceptions.cpp
In file included from ../../src/cppCORE/Exceptions.cpp:1:0:
../../src/cppCORE/Exceptions.h:5:19: fatal error: QString: No such file or directory
 #include <QString>
                   ^
compilation terminated.
make[2]: *** [Exceptions.o] Error 1
make[2]: Leaving directory `/home/jgsanders/git_sw/ngs-bits/build-tools-Linux-Release/cppCORE'
make[1]: *** [sub-cppCORE] Error 2
make[1]: Leaving directory `/home/jgsanders/git_sw/ngs-bits/build-tools-Linux-Release'
make: *** [build_tools_release] Error 2

**Comment by marc-sturm** [comment]
next you need Qt5 and all other dependencies as documented.

Am 04.02.2017 02:07 schrieb "Jon Sanders" <notifications@github.com>:
