### ISSUE TITLE
BedCoverage removes some of my input rows from its output?

### ISSUE THREAD

**Issue by amyhouseman** [imgag/ngs-bits#301]
Hello,

BedAnnotateGC keeps removing rows from my input bed file in its output.

I ran it like:

```
#!/bin/bash --login
#SBATCH -J AmyHouseman_BedCoverage
#SBATCH -o %x.stdout.%J.%N
#SBATCH -e %x.stderr.%J.%N
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH -p htc
#SBATCH --account=scw1581
#SBATCH --mail-type=ALL          # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=HousemanA@cardiff.ac.uk     # Where to send mail
#SBATCH --array=1-20
#SBATCH --mem-per-cpu=128GB
#SBATCH --qos=maxjobs500

module purge
module load singularity
module load parallel


# Set bash error trapping to exit on first error.
set -eu

cd /scratch/c.c21087028/

module load anaconda
source activate
conda activate CNVcalling

BAM_INPUTS=/scratch/c.c21087028/Polyposis_Exome_Analysis_E132/samtools/sort/{}PE_samtoolssorted_GCA_000001405.15_GRCh38_no_alt_analysis_set.bam
EXOME_IDs_FILE=/scratch/c.c21087028/Polyposis_Exome_Analysis_E132/RAW_input/qualimap_bestcov_IDs
BED_INPUT=/scratch/c.c21087028/Polyposis_Exome_Analysis_E132/clincnv/ClinCNV/samples/gcAnnotated.truseq-dna-exome-v1-2-hg38-noalts.bed
COV_OUTPUT=/scratch/c.c21087028/Polyposis_Exome_Analysis_E132/clincnv/ClinCNV/clincnv-output/BedCoverage-cov/{}ngsbits_bedcoverage.cov

sed -n "${SLURM_ARRAY_TASK_ID}p" $EXOME_IDs_FILE | parallel -j 1 "BedCoverage -bam $BAM_INPUTS -in $BED_INPUT -out $COV_OUTPUT"
```

wc -l on the following files:
Original input before BedAnnotateGC:
214208 truseq-dna-exome-v1-2-hg38-noalts.bed

BedAnnotateGC file:
214208 gcAnnotated.truseq-dna-exome-v1-2-hg38-noalts.bed

Example BedCoverage output file: 
**213609** E132-H-001-1_S96_L008_ngsbits_bedcoverage.cov

Can you help?
Thanks,
Amy

**Comment by marc-sturm** [comment]
Hi Amy,

I suspect there are overlapping region in the input BED file.
BedCoverage merges overlapping regions before doing the calculation.

You can check with "BedInfo -nomerge" if the BED file is already merged or not.

Best,
  Marc

**Comment by amyhouseman** [comment]
Hi Marc, 

Thanks for your help!

It says this:

```
(CNVcalling) [c.c21087028@cl1 BedAnnotateGC-bed]$ BedInfo -nomerge -in truseq-dna-exome-v1-2-hg38-noalts.bed 
Regions    : 214209
Bases      : 45403883
Chromosomes: 26 (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, X, Y, MT, 1_KI270711V1_RANDOM)

Is sorted  : no
Is merged  : no

Fragment size (min)  : 4
Fragment size (max)  : 55238
Fragment size (mean) : 211.96
Fragment size (stdev): 315.55
```

**Comment by marc-sturm** [comment]
The file contains overlapping regions.
Sorry, but BedCoverage will always merge overlapping regions into one region.

If this is intentioaly, you have to split the BED file into severl files that contain no overlapping regions, run BedCoverage and the re-combine them.

Best,
  Marc

**Comment by amyhouseman** [comment]
No worries, I will look into it more.

How can you tell it is overlapping from that output?

**Comment by marc-sturm** [comment]
You can run BedMerge and than look at the diff between input and output.

**Comment by marc-sturm** [comment]
I changed the behaviour to keep all input regions.
This is available in the master now and in the next release version.
