### ISSUE TITLE
GSvar: Problems starting version 2018_11

### ISSUE THREAD

**Issue by hofmannw** [imgag/ngs-bits#31]
Hello Marc,

After compiling the ngs-bits and starting GSvar on Windows with Qt 5.9.5, I get the follwing error:

`Runtime Error!
Program ngs-bits-2018_11\bin\GSvar,exe
This application has requested the Runtime to terminate it in an unusual way.
Please contact the applications's support team for more information`

I also tried compiling the most recent version ngs-bits-2018_11-122-gd854460. After starting GSvar and loading a .GSvar file, this error appears:

`Uncaught cppCORE exception
message: Could not connext ti the NGSD database 'ngsd'
file ..\..\src\cppNGSD\NGSD.cpp
line: 33`

GSvar is working with "NGSD_enabled=false" in the GSvar.ini file

Regards, Winfried

**Comment by marc-sturm** [comment]
Hi Winfried,

I would use the latest version only, 2018_11 is already outdated.
The latest version seems to work, but database settings for NGSD are probably missing/wrong in the settings.ini file.

Best,
  Marc

**Comment by hofmannw** [comment]
Thank you, Marc!

I can't find any mistake in the settings.ini file. Has something changed with the sql driver since the change to Qt 5.9.5? I' ll check the Qt-MySQL files.

Regards, Winfried

**Comment by marc-sturm** [comment]
Nothing changed, but you have to copy the driver DLLs to the new Qt installation:
https://github.com/imgag/ngs-bits/blob/master/doc/install_win.md

Best,
  Marc

**Comment by hofmannw** [comment]
Hi Marc,
meanwhile, I found that GSvar works now, but not in our Citrix enviromment (same ngsd-error). When using the ngs-bits portable, is it necessary to copy the libmysql.dll to the Windows-Directory?
Regards, Winfried

**Comment by marc-sturm** [comment]
Hi Winfried,

no, the DLL in the application folder should be enough.
This is what we have in the application folder:
![grafik](https://user-images.githubusercontent.com/5638144/52724160-1b945900-2faf-11e9-9037-5b2b057bb67f.png)

Best,
  Marc

**Comment by hofmannw** [comment]
Hello Marc, thanks. 
Except for qwt.dll (where is it from?), everything is present. Still the same problem. I'll check the network connections of the Citrix appllication server.
Regards,  Winfried

**Comment by marc-sturm** [comment]
Hi Winfried,

the qwt.dll is not needed.

Best,
  Marc

**Comment by hofmannw** [comment]
Thanks for the info, Marc!

Regards, Winfried

**Comment by hofmannw** [comment]
Hello Marc,

we still have the database connection Problem on the citrix server. I guess, it has something to do with the MS C++ libraries: On this constallation, GSvar ist working:
 
![grafik](https://user-images.githubusercontent.com/6311895/52844932-18f84780-3106-11e9-98ea-0620fc56143a.png)
Maybe something of the C++ libraries on the Citrix Server are outdated.

Regards, Winfried

**Comment by marc-sturm** [comment]
try dependency walker on the mysql DLL perhaps?

Best,
 Marc

**Comment by hofmannw** [comment]
thanks for the hint!

Regards, Winfried
