### ISSUE TITLE
Feature Request: GSvar QC-Plot for # high qual CNVs

### ISSUE THREAD

**Issue by alex-seitz** [imgag/ngs-bits#311]
Hello,
for QC-purposes, it would be great, if you could add a QC-plot for the number of high-quality CNVs for each sample (same like the variant count or the read count):
![grafik](https://user-images.githubusercontent.com/9316811/189314402-5c1a289a-dac1-44a4-b390-ead611911151.png)

This would help us a lot.

Thank you

Best,
Alexander Seitz

**Comment by marc-sturm** [comment]
We can add the this as a QC metric to the databases in the pipeline.
Maybe also correlation to reference samples.

**Comment by alex-seitz** [comment]
That would also be great :)

**Comment by marc-sturm** [comment]
Added new QC terms to ngs-bits: 684bb43b5f84201ed2958b07d6bed9468ba387d7

**Comment by marc-sturm** [comment]
Added import of new QC terms into NGSD: [d0851731ee4f6c25bd5237624f7268b859d4db7c](https://github.com/imgag/megSAP/commit/2538d17332ea0f16543549538e4a725a0f2cfbbe)

**Comment by marc-sturm** [comment]
Implementation finished and tested:
![grafik](https://user-images.githubusercontent.com/5638144/195556748-928348c0-6c7b-41f5-ab14-dc08d19d4aa5.png)
