### ISSUE TITLE
BedAnnotateGenes - not loading? Strange error

### ISSUE THREAD

**Issue by amy-houseman** [imgag/ngs-bits#327]
Hello,

I have previously used BedAnnotateGC and I think that is still fine but after creating my environment and installing via conda onto HPC linux centos:

```
module load anaconda
source activate
conda create --name CNVcalling
conda activate CNVcalling
conda install -c bioconda/label/cf201901 ngs-bits
```

then 

`BedAnnotateGenes`

I get this error:

```
QSqlDatabase: QMYSQL driver not loaded
QSqlDatabase: available drivers: QSQLITE
BedAnnotateGenes 2018_11
Exception: Could not connect to the NGSD database: 'ngsd'
Location : ../../src/cppNGSD/NGSD.cpp:28
```

Do you know what it means?

Thanks!
Amy

Sorry I just saw a previous issue about this, I will check that out!

**Comment by marc-sturm** [comment]
Hi Amy,

It means that the MySQL driver is missing. Try installing MySQL in the conda environment. If that does not fix the problem, the qt5 MySQL package has to be installed as well.

Best,
  Marc
