### ISSUE TITLE
Add support for input files via HTTP

### ISSUE THREAD

**Issue by marc-sturm** [imgag/ngs-bits#328]
Toolbase checks if input files are readable.
This fails of a URL with HTTP is given.

There are two places in ToolBase.cpp where QFileInfo is used, which has no support for HTTP.

![grafik](https://user-images.githubusercontent.com/5638144/194520252-b279062a-c2bd-4f27-8c24-0e51fabf81db.png)

Please fix this bug.

@MarvinDo test if implemented.

**Comment by ubuntolog** [comment]
The overhead is far too high, especially when dealing with large files. VersatileFile will be sending multiple Rage requests to the server and it will be taking too long to get all needed ranges. Simple implementation does not solve the problem. All the tools have to be adjusted to be able to send lists of ranges within one request
