### ISSUE TITLE
How big is the ngsd database file?

### ISSUE THREAD

**Issue by amy-houseman** [imgag/ngs-bits#331]
Hi,

How big is the ngsd database?

Thanks,
Amy

**Comment by marc-sturm** [comment]
Depends on how many samples you import.
Initially it is small, but each genome has 300k variants and each exome 120k variants.
So it grows rapidly with the number of samples.

Best,
  Marc

**Comment by amy-houseman** [comment]
Hi Marc,

When using for BedAnnotateGenes and just one bed file for annotation, how would that work when I am not importing any samples?

Thanks,
Amy

**Comment by marc-sturm** [comment]
Then it's small.

Please check "Initial import of data" here:
https://github.com/imgag/ngs-bits/blob/master/doc/install_ngsd.md

I think for BedAnnotateGenes you need to do the import steps until NGSDImportEnsembl  only, which saves some time.

**Comment by amy-houseman** [comment]
Hello, 

I've been working with my IT department to get ngs-bits onto our HPC in order to use BedAnnotateGenes. 

They have come to me and said:

I have performed the first import but the second seems to have a file which may be experiment specific e.g.
ngs-bits/bin/NGSDImportHGNC --help
If I run this it says 2 mandatory options
Mandatory parameters:
  -in <file>      HGNC flat file (download [ftp://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/tsv/hgnc_complete_set.txt](https://eur03.safelinks.protection.outlook.com/?url=ftp%3A%2F%2Fftp.ebi.ac.uk%2Fpub%2Fdatabases%2Fgenenames%2Fhgnc%2Ftsv%2Fhgnc_complete_set.txt&data=05%7C01%7Chousemana%40cwmwl.cardiff.ac.uk%7Ce0e0642283374f78453708dab6a428b0%7Cbdb74b3095684856bdbf06759778fcbc%7C1%7C0%7C638023113413105938%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=unfwytMMCpEdnu1CBG5HNkZdvISk6rKFM588LCxphKc%3D&reserved=0))
  -ensembl <file> Ensembl gene file (gff3) to resolve duplicate ENSG identifier.

**What would the ensembl option be?**

I am unsure, as the link just downloads ensembl files for me?

Thanks,
Amy

**Comment by marc-sturm** [comment]
The Ensembl option takes this file for HG38:
https://ftp.ensembl.org/pub/release-107/gff3/homo_sapiens/Homo_sapiens.GRCh38.107.chr.gff3.gz

I will update the documention.
