### ISSUE TITLE
NGSD Installation docu mistakes

### ISSUE THREAD

**Issue by alex-seitz** [imgag/ngs-bits#338]
Hi,
I just set up a new instance of the NGSD and realized the following mistakes in the docu/help outputs of the programs:

1. `NGSDImportHGNC` needs a gff from ensembl, but it is stated nowhere, which one. I'm guessing the one from `NGSDImportEnsembl`, but that program is called after `NGSDImportHGNC`, so it might not be obvious
2. The link to the file `gnomad.v2.1.1.lof_metrics.by_gene.txt.bgz` in `NGSDImportGeneInfo` is broken

Best,
Alex

**Comment by marc-sturm** [comment]
I fixed that:
https://github.com/imgag/ngs-bits/commit/430d9312dc2190c0b0a14159f00bb6b73f522c58
