### ISSUE TITLE
Replication hg19 to hg38

### ISSUE THREAD

**Issue by alex-seitz** [imgag/ngs-bits#341]
Hi,
I wanted to test the NGSD-replication from hg19 to 38, but I get the following error:
`Error: Exception: Column count doesn't match value count at row 1 QMYSQL3: Unable to prepare statement Query: INSERT INTO project VALUES (:id, :name, :aliases, :type, :internal_coordinator_id, :comment, :analysis, :preserve_fastqs, :email_notification)`
It looks like my hg19 db is missing the `archived` field in the `project` table.
However, I don't want to edit my production hg19 db to be able to migrate to hg38. (There are additional Warnings that columns are different between the two datbases, but that is expected, right?
Do you have any fix for me?

Best,
Alex

**Comment by marc-sturm** [comment]
Hi Alex,

the dialog assumes that the tables are the same in the two versions of NGSD.
Thus, the easiest solution is to adapt the hg19 NGSD.
Adding the archived field should not hurt.
If you want to be on the save side, create a copy of the production version, make the changes there und use it for migration.

Which other tables are different?

Best,
  Marc

**Comment by alex-seitz** [comment]
Hi, I get the following Warnings:

```
Warning: Table 'db_info' not in source database!
Warning: Table 'expression' not in source database!
Warning: Table 'expression_exon' not in source database!
Warning: Table 'report_configuration_other_causal_variant' not in source database!
Warning: Table 'somatic_pathway' not in source database!
Warning: Table 'somatic_pathway_gene' not in source database!
Warning: Table 'user_permissions' not in source database!
Warning: Table 'variant_literature' not in source database!
Warning: Table 'gene' has differing field list!
Warning: Table 'gene_transcript' has differing field list!
Warning: Table 'hpo_genes' has differing field list!
Warning: Table 'processed_sample' has differing field list!
Warning: Table 'project' has differing field list!
Warning: Table 'report_configuration_cnv' has differing field list!
Warning: Table 'report_configuration_sv' has differing field list!
Warning: Table 'report_configuration_variant' has differing field list!
Warning: Table 'sample' has differing field list!
Warning: Table 'sv_deletion' has differing field list!
Warning: Table 'sv_duplication' has differing field list!
Warning: Table 'sv_insertion' has differing field list!
Warning: Table 'sv_inversion' has differing field list!
Warning: Table 'sv_translocation' has differing field list!
Warning: Table 'variant' has differing field list!
Warning: Table 'variant_publication' has differing field list!
```

I'm guessing that the project is not the only one that will have to be adapted. Because of this, I will clone the production database and will use that one to do the adaptations. I can finally use that adapted one to test if the changes have any impact on the analyses.
I will keep you posted on the results

Best,
Alex

**Comment by marc-sturm** [comment]
Yes, that's probabliy the best strategy.

You can ignore all tables 'not in source database!'.
For the others you have to see if they make problems...

**Comment by alex-seitz** [comment]
Everything works as expected, I did not modify our production database, but keep running a script that automatically clones the production db and makes the needed changes (3 tables) to be able to use the replication.
Thank you
