### ISSUE TITLE
PERsim generating reads with an insert size of 0

### ISSUE THREAD

**Issue by stuckyb** [imgag/ngs-bits#35]
Hello,

First, thank you for providing the ngs-bits tools!  I have been experimenting with PERsim, and I noticed that it sometimes generates reads with insert sizes of 0.  Here is an example:
```
@PERsim:1:ABCDEF:1:mt_genome:3575:3574 1:N:0:AACGTGAT
AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGAGTTAAAAAAATACTAGATTAGACAGCTAAGTTAGAAACGTCTAAGAATCCACTGGTGTTATGAATTGAATTGGAACTGGAAAATAGAATTCGTAAGTGACTACGAACCGCAATA
+
AAAAAFFFFFFFGGGGGGFFFFFFFFFFEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

Is that a bug, or intended behavior?

Thank you for any help you can provide with this!

**Comment by marc-sturm** [comment]
Thanks. We're happy for every user!

the insert size is defined by the normal distribution given by `ins_mean` and `ins_stdev`.
This basically allows for any value, so I set the lower bound to 0, which is valid in FASTQ.

If this disturbs your downstream analysis, I can add a parameter for the minimal insert size.
As a quick fix, you can lower the `ins_stdev` parameter to something like 30, this makes insert size zero reads unlikely.

Best,
  Marc

**Comment by stuckyb** [comment]
Thanks for the quick reply!  Makes sense.  At first, I was thinking allowing inserts of size 0 was surely a bug, but I suppose that could happen in real sequencing if adapter dimers get sequenced.  (I think, anyway.)

**Comment by marc-sturm** [comment]
Yes, some protocols produce primer dimers and thus zero length inserts.

Can I close the issue then?

**Comment by stuckyb** [comment]
Yes, fine to close.  Thanks!
