### ISSUE TITLE
GSvar: Add burden test for genes

### ISSUE THREAD

**Issue by marc-sturm** [imgag/ngs-bits#357]
- allow definition of two cohorts (cases, controls)
  - allow selection by age (add year of birth from GenLab and used it to calcuate age based on sequencing date of sample)
- allow definition of filter criteria for variants
  - max gnomAD AF
  - max NGSD count
  - recessive mode
- calculate p-value for enrichment/burden in all/protein-coding genes

**Comment by leonschuetz** [comment]
- [ ] check input ps list for same processing system

- [ ] validate on positive controls (breast cancer, ...)

**Comment by leonschuetz** [comment]
- [ ] limit to high-confindent region 
    - [ ] 10x/20x coverage
    - [ ] exon region (paper from @GermanDemidov )
 
 - [ ] add rebel?
 
 - [ ] remove related samples

**Comment by GermanDemidov** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6589356/ this is CCR constrained regions and this is the burden test https://pubmed.ncbi.nlm.nih.gov/34571366/ which uses this map

**Comment by GermanDemidov** [comment]
I would add also ancestry selection (only EUR) and control selection (probably option)

**Comment by GermanDemidov** [comment]
Also p-values and actual contingency tables I'd put into the output for sure, currently I wanted to test the overall correctness of the test and could not, I need p-values for this...

**Comment by leonschuetz** [comment]
from #457:

Added exclusion region to burden test.
This is need to to exclude low coverage and low confidence regions.

- [ ] allow pasting a BED file
- [ ] show size of region in GUI
- [ ] filter out variants inside the region

**Comment by leonschuetz** [comment]
- [ ] additional/aternative to CCR: remove last (2) exon(s)

**Comment by GermanDemidov** [comment]
We are risking to overload the "control panel" with features, but I'd make 3 options: 1) remove last exon 2) remove 2 last exons 3) filter CCR regions up to (80%? or make it user-defined). Maybe one of the features would also be calculate adjusted p-values (for multiple comparison) - I believe this is the C++ implementation of a good method https://github.com/gatoravi/fdr/blob/master/bh-fdr.h
