### ISSUE TITLE
Determine gender not working in Server-Client mode

### ISSUE THREAD

**Issue by leonschuetz** [imgag/ngs-bits#362]
The Determine gender widget in GSvar at `Tools`> `Determine gender` > `Based on *` is not working.

Error message:
```
Execution failed: Could not read header from BAM/CRAM file http://gsvar.img.med.uni-tuebingen.de:8444/v1/temp/d10ca412-6a08-491e-b3f7-70fa1d658538/NA12878_58.bam?token=...
```

**Comment by ubuntolog** [comment]
I have found what is causing it: content-length header is incorrect. The fix will follow soon

**Comment by ubuntolog** [comment]
I have merged the fixed
