### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by dbalague** [imgag/ngs-bits#4]
I was trying to compile ngs-bits and I got into some compilation errors.

I could run `make build_3rdparty` and everything compiled with no problem. However, when running
`make build_tools_release` I got the following error:
```
icpc: command line warning #10155: ignoring option '-l'; argument required
icpc: error #10236: File not found:  'bamtools'
make[2]: *** [../../bin/libcppNGS.so.1.0.0] Error 1
make[2]: Leaving directory `/usr/local/ngs-bits/2.4.1/old/ngs-bits/build-tools-Linux-Release/cppNGS'
make[1]: *** [sub-cppNGS-make_first] Error 2
make[1]: Leaving directory `/usr/local/ngs-bits/2.4.1/old/ngs-bits/build-tools-Linux-Release'
make: *** [build_tools_release] Error 2
```
The error is clearly due to a space between `-l` and `bamtools`. A quick search in `ngs-bits` directory shows that there are five files with this issue:

```
src/cppNGSD-TEST/cppNGSD-TEST.pro:37:LIBS += -L$$PWD/../../bamtools/lib/ -l bamtools
src/app_cli.pri:24:LIBS += -L$$PWD/../bamtools/lib/ -l bamtools
src/app_gui.pri:28:LIBS += -L$$PWD/../bamtools/lib/ -l bamtools
src/cppNGS-TEST/cppNGS-TEST.pro:28:LIBS += -L$$PWD/../../bamtools/lib/ -l bamtools
src/cppNGS/cppNGS.pro:30:LIBS += -L$$PWD/../../bamtools/lib/ -l bamtools
```

Once I removed the space, the code compiled with no errors.

**Comment by imgag** [comment]
Hi Daniel,

thanks for the bug report.
I guess noone has tried compiling ngs-bits with the intel compiler yet.
I just committed a fix.

Can you verify that it works out of the box now?

Best,
  Marc

**Comment by imgag** [comment]
I assume the fix worked.

**Comment by dbalague** [comment]
Sorry for the late reply. I have not had a chance to try it again until
today. It does work out of the box with Intel compilers now.

Best,
Daniel
