### ISSUE TITLE
MappingQC: nan-error

### ISSUE THREAD

**Issue by th-koechling** [imgag/ngs-bits#41]
Dear developers,

using MappingQC as part of a variant calling pipeline, the following error message turns up from time to time. 

Might this be something to consider or just a plot that is not being generated properly?

Kind regards,

Thorsten

MappingQC 2018_06
Programming exception: Could not execute python script:
/tmp/cpVB9zzmkx7g1gU5.py
 Error message is: Traceback (most recent call last):
  File "/tmp/cpVB9zzmkx7g1gU5.py", line 7, in <module>
    plt.plot([2.5,7.5,12.5,17.5,22.5,27.5,32.5,37.5,42.5,47.5,52.5,57.5,62.5,67.5,72.5,77.5,82.5,87.5,92.5,97.5,102.5,107.5,112.5,117.5,122.5,127.5,132.5,137.5,142.5,147.5,152.5,157.5,162.5,167.5,172.5,177.5,182.5,187.5,192.5,197.5,202.5,207.5,212.5,217.5,222.5,227.5,232.5,237.5,242.5,247.5,252.5,257.5,262.5,267.5,272.5,277.5,282.5,287.5,292.5,297.5,302.5,307.5,312.5,317.5,322.5,327.5,332.5,337.5,342.5,347.5,352.5,357.5,362.5,367.5,372.5,377.5,382.5,387.5,392.5,397.5,402.5,407.5,412.5,417.5,422.5,427.5,432.5,437.5,442.5,447.5,452.5,457.5,462.5,467.5,472.5,477.5,482.5,487.5,492.5,497.5,502.5,507.5,512.5,517.5,522.5,527.5,532.5,537.5,542.5,547.5,552.5,557.5,562.5,567.5,572.5,577.5,582.5,587.5,592.5,597.5,602.5,607.5,612.5,617.5,622.5,627.5,632.5,637.5,642.5,647.5,652.5,657.5,662.5,667.5,672.5,677.5,682.5,687.5,692.5,697.5,702.5,707.5,712.5,717.5,722.5,727.5,732.5,737.5,742.5,747.5,752.5,757.5,762.5,767.5,772.5,777.5,782.5,787.5,792.5,797.5,802.5,807.5,812.5,817.5,822.5,827.5,832.5,837.5,842.5,847.5,852.5,857.5,862.5,867.5,872.5,877.5,882.5,887.5,892.5,897.5,902.5,907.5,912.5,917.5,922.5,927.5,932.5,937.5,942.5,947.5,952.5,957.5,962.5,967.5,972.5,977.5,982.5,987.5,992.5,997.5],[nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan], label='')
NameError: name 'nan' is not defined

Location             : ../../src/cppCORE/LinePlot.cpp:138
This should not happen, please report the error to the developers!

**Comment by marc-sturm** [comment]
Hi Thorsten,

this should not happen.
It is probably a problem with bad data, but still it should be handled more gracefully.

What is the exact command line call you use?

Can you share the data and with us? Otherwise, debugging will not be possible...

Best,
  Marc

**Comment by th-koechling** [comment]
Hi Marc,

You are right, bad data was causing the crash. I re-analyzed the sample set where I had seen the error message and it turned out the affected samples were those consisting of very low read numbers (about 10 reads per fastq file). That resulted in a probably correctly formatted but useless BAM file. The missing MappingQC log file is not a problem for our analysis as those samples are not useable anyway. 

The command line call was:

`MappingQC -in sorted.bam -wgs -out mapping_qc.xml`

I can't send you the raw data but I was able to reproduce the behavior using simulated Illumina reads. Please let me know if you would like me to send you the (very small)  BAM file. 

Thanks for your quick help and your great software! 

With kind regards

Thorsten

**Comment by marc-sturm** [comment]
Hi Thorsten,

yes, please send me the simulated data then.
I will fix the bug asap.

Best,
  Marc

**Comment by th-koechling** [comment]
Hi Marc, 
here is the mini bam.
Viele Grüße
Thorsten


[TEST_sorted_bam.zip](https://github.com/imgag/ngs-bits/files/3362890/TEST_sorted_bam.zip)

**Comment by marc-sturm** [comment]
Hi Thorsten,

jetzt crasht es zumindest nicht mehr :)

Viele Grüße,
  Marc

**Comment by th-koechling** [comment]
Hallo Marc,
vielen Dank und viele Grüße!
Thorsten
