### ISSUE TITLE
Error when performing ancestry check

### ISSUE THREAD

**Issue by marc-sturm** [imgag/ngs-bits#415]
In the client-server version there is a bug in"Tools > Sample Ancestry". When using the tool with any sample, e.g. NA12878_45, you get an error:
![grafik](https://user-images.githubusercontent.com/5638144/229075340-181be77e-4993-48a2-9b9b-bf5b55c17766.png)

The problem is that reading VCF.GZ over https is not implemented (see VcfFile.cpp:405)

**Comment by ubuntolog** [comment]
Fixed by using temporary files
