### ISSUE TITLE
GSvar: add REs to report config

### ISSUE THREAD

**Issue by marc-sturm** [imgag/ngs-bits#421]
Before this issue:
- [x] decide with REs should be called in short-read and long-read genomes (clear disease association)
- [x] collect/update meta data: cutoffs, repeat-structure, inheritance, disease name(s), HPO-terms

ToDos SR:
- [x] make separate step in megSAP
  - [x] update steps in GSvar.ini
  - [x] re-calulcate for all diagnostic genomes
    - [x] import into NGSD
- [x] add distribution plots to GSvar
  - [x] set outlier cutoffs in NGSD and use in GSvar
  - [x] make distribution plots system-specific
- [x] compare to NGS and FLA lengths
- [x] add RE callset table
  - [x] re-import WGS calls to add callset 
  - [x] call WES samples and import
- [x] allow report config for REs
  - [x] add to report HTML
  - [x] add to report XML
  - [x] correct report configs ("other causal variant > RE" to report config for RE)
    - [x] - remove 'RE' as as type to report_configuration_other_causal_variant 
  - [x] add causal RE for WES/WGS/lrGS samples to NGSD
- [x] update RE docu of GSvar
 
ToDos LR:
- [x] update RE catalog
- [x] make separate step in megSAP
  - [x] update steps in GSvar.ini
  - [x] re-calulcate for all diagnostic genomes
    - [x] import into NGSD
    - [x] set statistical cutoff in NGSD

**Comment by leonschuetz** [comment]
Evaluate tools:
    - [ ]  [PathSTR](https://www.medrxiv.org/content/10.1101/2024.03.06.24303700v1.full.pdf)
    - [ ] LongTR
