### ISSUE TITLE
Path to GSvar INI incorrect

### ISSUE THREAD

**Issue by alex-seitz** [imgag/ngs-bits#43]
Hi,
I just recompiled the latest version of megSAP and GSvar (release 2019_08, as described in the docu for kompilation under Windows)
When I want to start GSVar, I get the following Error message:
![GSVAR_ini_error](https://user-images.githubusercontent.com/9316811/62699740-882d6500-b9e0-11e9-8990-f7c850d812ba.PNG)
It appears it can't get the correct path to the folder it resides in.

Best,
Alex

**Comment by marc-sturm** [comment]
Hi Alex,

is the `GSvar.ini` file in the folder and does it contain the `igv_genome` entry?

In our installation it looks like this:
```
[General]
igv_genome=\\\\SRV024\\Netzanwendungen\\IGV\\genome\\1kg_v37_ensembl.genome
```

btw, the installations to build a IVG genome file that contains Ensembl transcripts can be found here:
https://github.com/imgag/IGV_genome_ensembl

Best,
  Marc

**Comment by alex-seitz** [comment]
Hi Marc,
yes, the GSvar.ini did contain the igv_genome entry.
Additionally, I deleted the old `GSvar.ini` and `settings.ini` in the hope that it will use the `*.bak` files where everything should work, right?
I still get the same error.

Best,
Alex

**Comment by marc-sturm** [comment]
Strange, can you please call me:
07071 29-85026
