### ISSUE TITLE
NGSDImportHPO new format for phenotype_to_genes.txt

### ISSUE THREAD

**Issue by alex-seitz** [imgag/ngs-bits#430]
Hi,
the file format for the `phenotype_to_genes.txt` has changed:
the last 3 columns (the disease information) was removed. Just adding empty columns does not work, as you use this phenotype information for parsing.

Best,
Alex

**Comment by marc-sturm** [comment]
With the new file the number of gene-HPO associations drops from 362k to 261k because of the missing disease information we use.

I would not update to a new `phenotype_to_genes.txt` file until we have evaluated what effect this change has.

**Comment by marc-sturm** [comment]
Changes so far in branch https://github.com/imgag/ngs-bits/tree/HPO_phenotype_to_genes

**Comment by marc-sturm** [comment]
Waiting for reply from HPO people...

**Comment by marc-sturm** [comment]
They will not answer I guess.

I will just test which effect this change has based on the causal variant ranking.

Wait until NGSD is switched to SRV001 - then we can use the old NGSD as test database.

**Comment by alex-seitz** [comment]
They changed the format again and re-added the OMIM/ORPHA-IDs but left the Additional infos and the source columns out. Otherwise it seems to work again

**Comment by marc-sturm** [comment]
Hi Alex,

I updated the import tool in the master:
https://github.com/imgag/ngs-bits/commit/24c9b095b8b07e2b239862b1e08560620cf4598f

Can you test if it works for you as well please?

Best,
  Marc

**Comment by alex-seitz** [comment]
Yes, I will try it and let you know

**Comment by marc-sturm** [comment]
thanks. It looks ok then.

Just re-open the issue if there are problems in the future!
