### ISSUE TITLE
 BedAnnotateGenes   Requested key 'ngsd_host' not found in settings

### ISSUE THREAD

**Issue by 897891211** [imgag/ngs-bits#437]
(ngs-bits) [root@host /]#  BedAnnotateGenes 2023_02
Programming exception: Requested key 'ngsd_host' not found in settings!
Location             : ../../src/cppCORE/Settings.cpp:235
This should not happen, please report the error to the developers!

Mysql  Configuration already installed,  but  When running commands  "BedAnnotateGenes"  , Command line blank directly .like this

(ngs-bits) [root@host /]#   BedAnnotateGenes

**Comment by ubuntolog** [comment]
It seems like your configuration file (settings.ini) is incomplete. "ngsd_host" parameter should have the host name or IP address of the server where your database is running. Port number and database credentials should also be set. Please check the config.

**Comment by 897891211** [comment]
IP address and Port numbe  Already set .  How should I set database credentials ?  This is my  configuration (settings.ini):

############################# public settings #############################
#          Common settings that need to be set for many tools             #
###########################################################################

#Path to the reference genome FASTA file for GRCh38
reference_genome = ""

#Data for lift-over between genome builds (GRCh38 <> GRCh19)
reference_genome_hg19 = ""
liftover_hg19_hg38 = ""
liftover_hg38_hg19 = ""

############################ internal settings ############################
#   If you do not know what these settings mean, leave them unchanged!    #
###########################################################################

#NGSD MySQL credentials
ngsd_host = "192.168.66.202"
ngsd_port = 3306
ngsd_name = "ngsd"
ngsd_user = "ngsduser"
ngsd_pass = "123456"

ngsd_test_host = ""
ngsd_test_port = 3306
ngsd_test_name = ""
ngsd_test_user = ""
ngsd_test_pass = ""

#GL8 MySQL credentials
genlab_mssql = false
genlab_host = ""
genlab_port = 3306
genlab_name = ""
genlab_user = ""
genlab_pass = ""

#megSAP folders
projects_folder_diagnostic = "";
projects_folder_research = "";
projects_folder_test = "";
projects_folder_external = "";
data_folder = ""

#setting for variant scoring/ranking
ranking_variant_blacklist=

#python executable for plotting (set if the python exe is not in the PATH)
python_exe = ""

**Comment by ubuntolog** [comment]
"ngsd_name" should contain your database name, "ngsd_user" is a database user, "ngsd_pass" is a password. The tool you are trying to start makes an attempt to connect to a database and fails

**Comment by 897891211** [comment]
The problem remains the same, but thank you very much！

**Comment by ubuntolog** [comment]
Are you still getting exactly the same error message about "ngsd_host" not being set? Sorry, you have not provided enough information about the issue.

**Comment by 897891211** [comment]
hello ,&nbsp; this is my running command ：
BedAnnotateGenes&nbsp; -in&nbsp; gcAnnotated.bed&nbsp; -out&nbsp; test.bed




My problem is：“The gene column has not been annotated”.


setting.ini&nbsp; 

#Data for lift-over between genome builds (GRCh38 <&gt; GRCh19)
reference_genome_hg19 = ""
liftover_hg19_hg38 = ""
liftover_hg38_hg19 = ""


#NGSD MySQL credentials
ngsd_host = "192.168.66.202"
ngsd_port = 3306
ngsd_name = "ngsd"
ngsd_user = "ngsduser"
ngsd_pass = "123456"     






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "imgag/ngs-bits"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月5日(星期一) 晚上7:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [imgag/ngs-bits]  BedAnnotateGenes   Requested key 'ngsd_host' not found in settings (Issue #437)





 
Are you still getting exactly the same error message about "ngsd_host" not being set? Sorry, you have not provided enough information about the issue.

**Comment by 897891211** [comment]
hello ,&nbsp; this is my running command ：
BedAnnotateGenes&nbsp; -in&nbsp; gcAnnotated.bed&nbsp; -out&nbsp; test.bed




My problem is：“The gene column has not been annotated”.


setting.ini&nbsp; 

#Data for lift-over between genome builds (GRCh38 <&gt; GRCh19)
reference_genome_hg19 = ""
liftover_hg19_hg38 = ""
liftover_hg38_hg19 = ""


#NGSD MySQL credentials
ngsd_host = "192.168.66.202"
ngsd_port = 3306
ngsd_name = "ngsd"
ngsd_user = "ngsduser"
ngsd_pass = "123456"     






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "imgag/ngs-bits"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月5日(星期一) 晚上7:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [imgag/ngs-bits]  BedAnnotateGenes   Requested key 'ngsd_host' not found in settings (Issue #437)





 
Are you still getting exactly the same error message about "ngsd_host" not being set? Sorry, you have not provided enough information about the issue.

**Comment by 897891211** [comment]
hello,  There is currently no 'ngsd_host' reported  Wrong, but directly running 'BedAnnotateGenes' results in blank output.
When I conducted the experiment, the results were as follows.
This is my running command ：
BedAnnotateGenes   -in   gcAnnotated.bed   -out     test.bed

`[master ll]$  head gcAnnotated.bed`
`chr1   18963   19169    0.5340`
`chr1   24260   24532    0.4706`
`[master ll]$  head test.bed`
`chr1  12080    12251    0.4912`
`chr1  12595    12802    0.6232`

My current problem is：“The gene column has not been annotated”.
Do you know the reason for this?     Where is not set correctly?

Thank you.


setting.ini
#Data for lift-over between genome builds (GRCh38 <> GRCh19)
reference_genome_hg19 = ""
liftover_hg19_hg38 = ""
liftover_hg38_hg19 = ""

#NGSD MySQL credentials
ngsd_host = "192.168.66.202"
ngsd_port = 3306
ngsd_name = "ngsd"
ngsd_user = "ngsduser"
ngsd_pass = "123456"

**Comment by marc-sturm** [comment]
Hi,

you need to create and fill the database as described here:
https://github.com/imgag/ngs-bits/blob/master/doc/install_ngsd.md#initial-import-of-data

Best,
  Marc

**Comment by ubuntolog** [comment]
I suggest we should close the issue, since the original problem stated in the caption has been resolved. A separate issue can be created, if there is something else not working.
