### ISSUE TITLE
heterozygous variant count too high (because of mosaic variant calling)

### ISSUE THREAD

**Issue by alex-seitz** [imgag/ngs-bits#438]
Hi,
because of the mosaic variants, we have the problem that some variants are removed from the filter, because they are too often called as mosaics (one example 12 times heterozygous without mosaic and 3716 heterozygous with mosaic)
Would it be possible to

 a) get an additional annotation column for hom het and mos? So the filter for the NGSD counts can be used again?
 b) exclude the count of the mosaic variants

We would prefer the (a) version

Best,
Alex

Todos (Marc):
- [x] NGSD: add germline_mosaic column to variant table
- [x] NGSDExportAnntationData: Count/export out mosaic variants separately
- [x] megSAP: add mosaic colum to output of vcf2gsvar
- [x] GSvar: add option to count mosaic variant as heterozygous in NGSD count filter
- [x] GSvar: show counts separately in variant tab

**Comment by marc-sturm** [comment]
Hi Alex,

can you please tell me the variant that is affected by this? Is it a indel?

Best,
  Marc

**Comment by alex-seitz** [comment]
Hi Marc,
I did a quick checks: When I look at variants that 
- have count > 1000 with mosaics
- have count < 1000 without mosaics
- have a difference between mosaics and without mosaics of at least 500
I get around 1500 variants, 280 of them being snvs, the rest indels.
If you want, I can send you these variants so you can have a look at them?

Best,
Alex

**Comment by marc-sturm** [comment]
Yes, a few examples would be nice.

I can split counts to hom/het/mosaic in NGSD, Variant tab, NGSD export and megSAP annotation.
Then one can filter with or without mosaic variants.

**Comment by alex-seitz** [comment]
That would be great,
I will send you the file

**Comment by marc-sturm** [comment]
implemented megSAP changes:
https://github.com/imgag/megSAP/commit/da81ea78a9c3ca6b571c6881adfd2621cd8d7df5
