### ISSUE TITLE
Problem with ambiguous Genesymbols

### ISSUE THREAD

**Issue by alex-seitz** [imgag/ngs-bits#44]
Hey,
There is a problem with ambiguous symbols in the filtering of GSvar and ngs-bits in general
Example:
In one of the latest HGNC updates, the symbol QARS was changed to QARS1. However, sometime in the past there was another gene symbol named QARS with was changed to EPRS.
Thus, currently it is not possible to automatically differentiate between the two.
Now, the HPO-Terms still have the old name of "QARS". However, when trying to filter with Phenotypes (e.g. "Sloping forehead") the gene is completely missing from the filtering (the NA12878 has at least one mutation in this gene:
`chr3	49141116	49141116	G	A	hom)`
If a gene can't be mapped to a correct one, maybe the filtering step should show both (all) possibilities instead of none?

Additionally, the file downloaded for the HPO integration uses some old and wrong names, which you might resolve yourself:
COX1 -> MT-CO1 
TRNP -> MT-TP
COX2 -> MT-CO2
QARS -> QARS1
ND1  -> MT-ND1

I had to manually adapt the `ALL_SOURCES_ALL_FREQUENCIES_diseases_to_genes_to_phenotypes.txt` file, otherwise these symbols would not be imported and thus would be missing when filtering the corresponding HPO terms.
Be careful with the adaption, as there are e.g. other genes starting with "COX1" so you can't just change them as easily.

Best,
Alex

**Comment by marc-sturm** [comment]
Hi Alex.

two days ago i fixed the import of Ensembl transcripts for QARS1.
It now works because Ensembl provides the HGNC id in addition to the gene name:
https://github.com/imgag/ngs-bits/commit/e422443f16700b23116829c0a7f109c465daff72

Unfortunately this does not fix the HPO import.

We have to inform the HPO creators of the outdated gene names.
That's the only long-term solution I can think of...

Best,
  Marc

**Comment by alex-seitz** [comment]
Ok, great,
however, the problem with the outdated genenames will always be a problem, because there probably will always be a problem. Thus your GenesToBe should return all possible regions and not remove it completely.

Best,
Alex

**Comment by marc-sturm** [comment]
I created an issue in the HPO project:
https://github.com/obophenotype/human-phenotype-ontology/issues/4916

**Comment by marc-sturm** [comment]
I will add an option "replace_ambiguous" to "GenesToApproved".

It will report current error cases, e.g.

> COX2 ERROR: COX2 is a synonymous symbol of the genes MT-CO2, PTGS2

in this form:

> MT-CO2 REPLACED: COX2 is a synonymous symbol of the genes PTGS2
> PTGS2 REPLACED: COX2 is a synonymous symbol of the genes PTGS2

Then, the output of GenesToApproved can be fed to GenesToBed.
Does that sound good?

**Comment by alex-seitz** [comment]
This looks great
Thank you

**Comment by marc-sturm** [comment]
Implemented in 9535d0e832639dc643e905e101f9f74034d4f125
