### ISSUE TITLE
Inconsistencies in HPO-Import

### ISSUE THREAD

**Issue by alex-seitz** [imgag/ngs-bits#46]
Hi,
we realized there are some inconsistencies in the HPO-Import.
In the "Inheritance terms" you import the name directly as is from the given file and in all other cases, you first run a genes2approved function. Thus you sometimes import the old and sometimes the current symbol.
Is there a specific reason for this?
Interestingly, checking the same term-id in GSvar, the current symbol is shown, whereas the old symbol is written in the database.

Best,
Alex

**Comment by marc-sturm** [comment]
Hi Alex,

do you have an example?
I will check on the weekend.

Best,
  Marc

**Comment by alex-seitz** [comment]
Hi Marc,
I don't know when you last importet, one example of ours is AARS and AARS1.
The problems are in the main.cpp of NGSDImportHPO:
In line 188 you create a variable inheritance_terms
in line 205 you check for this variable and then import the gene directly
In line 225 you use the gene_db_id, which is the result of genes2approved from line 200
Basically it should be
`db.geneSymbol(gene_db_id)`
instead of
`gene`
in line 211
Except if you have a reason for using the original gene symbols in the inheritance cases?
Best,
Alex

**Comment by marc-sturm** [comment]
Hi Alex,

thanks for reporting this.
It's fixed.

Best,
  Marc
