### ISSUE TITLE
NGSDImportOrpha can't import old gene-names

### ISSUE THREAD

**Issue by alex-seitz** [imgag/ngs-bits#49]
Hello,
when I run the current ORPHA-Import, I get several errors like this:

`Warning: Skipping non-approved gene name 'GARS' for term 'ORPHA:99938'!`

This example is a problem with old gene names. The current one (and one in the database) is GARS1.

In the ORPHA import, an additional call of genes2approved of the input would allow for the input of genes where the ORPHA-data does not contain the current gene-symbol.
If I read this correctly, this should be used in line 72 of the main.cpp.

Best,
Alex

**Comment by marc-sturm** [comment]
Thanks Alex,

it is fixed in ca0c1bd46718448942271cc8529465911a6e4fa4

Best,
  Marc
