### ISSUE TITLE
Compile Error - undefined reference to `curl_easy_getinfo@CURL_OPENSSL_4’

### ISSUE THREAD

**Issue by HandsYe** [imgag/ngs-bits#524]
g++ -Wl,-rpath,'$ORIGIN' -Wl,-O1 -Wl,-rpath,/home/kpyj/anaconda3/lib -o ../../bin/cppREST-TEST main.o moc_HtmlEngine_Test.o moc_HttpProcessor_Test.o moc_RequestParser_Test.o moc_ServerHelper_Test.o moc_UrlManager_Test.o   -L/data/Software/ngs-bits/ngs-bits/src/../bin -lcppCORE -lcppXML -lcppNGS -L/data/Software/ngs-bits/ngs-bits/src/../htslib/lib/ -lhts -lz -L/data/Software/ngs-bits/ngs-bits/src/cppREST-TEST/../bin -lcppNGSD -lcppREST /home/kpyj/anaconda3/lib/libQt5Network.so /home/kpyj/anaconda3/lib/libQt5Sql.so /home/kpyj/anaconda3/lib/libQt5Core.so -lpthread
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_easy_getinfo@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_multi_perform@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_multi_cleanup@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_global_init@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_multi_info_read@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_easy_duphandle@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_easy_strerror@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_easy_setopt@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_easy_init@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_multi_fdset@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_multi_add_handle@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_multi_remove_handle@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_easy_cleanup@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_multi_init@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_easy_pause@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_share_cleanup@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_multi_timeout@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_multi_strerror@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_version_info@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_share_init@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_share_setopt@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_easy_reset@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/../bin/libhts.so: undefined reference to `curl_global_cleanup@CURL_OPENSSL_4'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:292: ../../bin/cppREST-TEST] Error 1
make[2]: Leaving directory '/data/Software/ngs-bits/ngs-bits/build-libs-Linux-Release/cppREST-TEST'
make[1]: *** [Makefile:255: sub-cppREST-TEST-make_first] Error 2
make[1]: *** Waiting for unfinished jobs....
g++ -Wl,-rpath,'$ORIGIN' -Wl,-O1 -Wl,-rpath,/home/kpyj/anaconda3/lib -o ../../bin/cppNGS-TEST main.o moc_Chromosome_Test.o moc_BedLine_Test.o moc_BedFile_Test.o moc_VariantList_Test.o moc_FilterCascade_Test.o moc_ChromosomalIndex_Test.o moc_Statistics_Test.o moc_Variant_Test.o moc_NGSHelper_Test.o moc_FastqFileStream_Test.o moc_FastaFileIndex_Test.o moc_QCCollection_Test.o moc_StatisticsReads_Test.o moc_GeneSet_Test.o moc_OntologyTermCollection_Test.o moc_BamReader_Test.o moc_CnvList_Test.o moc_StructuralVariantType_Test.o moc_Transcript_Test.o moc_BedpeLine_Test.o moc_BedpeFile_Test.o moc_Sequence_Test.o moc_VcfLine_Test.o moc_VcfFile_Test.o moc_VariantScores_Test.o moc_BamWriter_Test.o moc_SomaticVariantInterpreter_Test.o moc_Graph_Test.o moc_ChainFileReader_Test.o moc_BigWigReader_Test.o moc_VariantHgvsAnnotator_Test.o moc_TabIndexedFile_Test.o   -L/data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin -lcppCORE -L/data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../bin -lcppXML -lcppNGS -L/data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../htslib/lib/ -lhts -lz /home/kpyj/anaconda3/lib/libQt5Network.so /home/kpyj/anaconda3/lib/libQt5Core.so -lpthread
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_easy_getinfo@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_multi_perform@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_multi_cleanup@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_global_init@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_multi_info_read@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_easy_duphandle@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_easy_strerror@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_easy_setopt@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_easy_init@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_multi_fdset@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_multi_add_handle@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_multi_remove_handle@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_easy_cleanup@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_multi_init@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_easy_pause@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_share_cleanup@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_multi_timeout@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_multi_strerror@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_version_info@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_share_init@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_share_setopt@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_easy_reset@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGS-TEST/../../bin/libhts.so: undefined reference to `curl_global_cleanup@CURL_OPENSSL_4'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:372: ../../bin/cppNGS-TEST] Error 1
make[2]: Leaving directory '/data/Software/ngs-bits/ngs-bits/build-libs-Linux-Release/cppNGS-TEST'
make[1]: *** [Makefile:155: sub-cppNGS-TEST-make_first] Error 2
g++ -Wl,-rpath,'$ORIGIN' -Wl,-O1 -Wl,-rpath,/home/kpyj/anaconda3/lib -o ../../bin/cppNGSD-TEST main.o moc_ExportcBioPortal_Test.o moc_NGSD_Test.o moc_FileLocationProvider_Test.o moc_FileLocation_Test.o moc_GenLabDB_Test.o moc_ReportConfiguration_Test.o   -L/data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin -lcppCORE -L/data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../bin -lcppXML -lcppNGS -lcppNGSD -L/data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../htslib/lib/ -lhts -lz /home/kpyj/anaconda3/lib/libQt5Sql.so /home/kpyj/anaconda3/lib/libQt5Network.so /home/kpyj/anaconda3/lib/libQt5Core.so -lpthread
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_easy_getinfo@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_multi_perform@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_multi_cleanup@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_global_init@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_multi_info_read@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_easy_duphandle@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_easy_strerror@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_easy_setopt@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_easy_init@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_multi_fdset@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_multi_add_handle@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_multi_remove_handle@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_easy_cleanup@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_multi_init@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_easy_pause@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_share_cleanup@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_multi_timeout@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_multi_strerror@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_version_info@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_share_init@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_share_setopt@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_easy_reset@CURL_OPENSSL_4'
/usr/bin/ld: /data/Software/ngs-bits/ngs-bits/src/cppNGSD-TEST/../../bin/libhts.so: undefined reference to `curl_global_cleanup@CURL_OPENSSL_4'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:294: ../../bin/cppNGSD-TEST] Error 1
make[2]: Leaving directory '/data/Software/ngs-bits/ngs-bits/build-libs-Linux-Release/cppNGSD-TEST'
make[1]: *** [Makefile:205: sub-cppNGSD-TEST-make_first] Error 2
make[1]: Leaving directory '/data/Software/ngs-bits/ngs-bits/build-libs-Linux-Release'
make: *** [Makefile:55: build_libs_release] Error 2

**hi，how to solve this error ？ 
please help me.
thx.**

**Comment by marc-sturm** [comment]
Looks like libcurl is not installed.

Did you install all dependencies listed here?
https://github.com/imgag/ngs-bits/blob/master/doc/install_unix.md

It might me easier to use the pre-compiled binaries from Bioconda:
https://github.com/imgag/ngs-bits/blob/master/doc/install_bioconda.md

Best,
  Marc

**Comment by HandsYe** [comment]
But I have already downloaded this package.
![image](https://github.com/imgag/ngs-bits/assets/24598021/cef112cf-9281-4877-9f82-fd129c002d60)
regards
Ye

**Comment by marc-sturm** [comment]
Sorry, I cannot help you any further then.
You have to google the errors and you OS version to try and find a solution.

Or use bioconda.

Best,
  Marc
