### ISSUE TITLE
GSVar: Make `KeepFastq` of NovaSeqX SampleSheet export configurable in settings

### ISSUE THREAD

**Issue by BeneKenobi** [imgag/ngs-bits#529]
We only archive BAM/CRAM files thus we do not need intermediate FastQs. Please make this option configurable to save some precious disk space. 😉 

https://github.com/imgag/ngs-bits/blob/554919ea577fa225a05c815bc0bf567909f66927/src/cppNGSD/NGSD.cpp#L5644

**Comment by leonschuetz** [comment]
started implementaion in https://github.com/imgag/ngs-bits/tree/Samplesheet_extension

**Comment by leonschuetz** [comment]
inplemented in 9ac31bb21b31e362666844698fb22997cb892018, parameter can be set in the `settings.ini`
