### ISSUE TITLE
Confirm that the instructions for building ngs-bits from sources (Linux/MacOS) still works

### ISSUE THREAD

**Issue by luskx016** [imgag/ngs-bits#545]
Can you confirm the instructions for building from sources still works? I am trying to build from source in a docker image and cannot get it to work. I think I am following the instructions exactly. The error I cannot get past is this:

119.4 Info: creating stash file /home/results/ngs-bits/build-libs-Linux-Release/.qmake.stash
119.5 make[1]: Entering directory '/home/results/ngs-bits/build-libs-Linux-Release'
119.6 cd cppCORE/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/results/ngs-bits/src/cppCORE/cppCORE.pro CONFIG-=debug CONFIG+=release DEFINES+=QT_NO_DEBUG_OUTPUT ) && make -f Makefile 
119.6 Cannot find file: c.
119.6 make[1]: *** [Makefile:55: sub-cppCORE-make_first] Error 2
119.6 make[1]: Leaving directory '/home/results/ngs-bits/build-libs-Linux-Release'
119.6 make: *** [Makefile:55: build_libs_release] Error 2

The file  /home/results/ngs-bits/src/cppCORE/cppCORE.pro does not exist. Thanks!

**Comment by marc-sturm** [comment]
Hi,

the instructions should still work.

Unfortunately the error message is very cryptic, so I cannot give you any advice how to fix it.

Best,
  Marc

**Comment by ubuntolog** [comment]
It is possible that sub-modules are missing. Make sure you cloned the repository correctly. 

git submodule update --recursive --init
