### ISSUE TITLE
Wrong libraries when "making GSvar portable" (Windows)

### ISSUE THREAD

**Issue by alex-seitz** [imgag/ngs-bits#60]
Hey,
when I followed the instructions for Windows to make GSvar portable, I got errors that specific libraries could not be found:

<img src="https://user-images.githubusercontent.com/9316811/85367682-00821380-b52a-11ea-9e2a-27a2901003fa.png" width="400">

In the Documentation it says that you need the `Qt5Charts.dll` instead of the `Qt5Chartsd.dll`

The same is true for the following (from `C:\Qt\Qt5.9.5\5.9.5\mingw53_32\bin\`):
`Qt5Charts.dll -> Qt5Chartsd.dll`
`Qt5Core.dll -> Qt5Cored.dll`
`Qt5Gui.dll -> Qt5Guid.dll`
`Qt5Network.dll -> Qt5Networkd.dll`
`Qt5PrintSupport.dll -> Qt5PrintSupportd.dll`
`Qt5Sql.dll -> Qt5Sqld.dll`
`Qt5Widgets.dll -> Qt5Widgetsd.dll`
`Qt5Xml.dll -> Qt5Xmld.dll`
`Qt5XmlPatterns.dll -> Qt5XmlPatternsd.dll`

Additionally, would it be possible to order the libraries in the table alphabetically, this makes it a lot easier to extract them from the directories.

Thank you

Alex

**Comment by marc-sturm** [comment]
Hi Alex,

you have to build in release mode, then the DLL names are correct.
The DLLs with suffix 'd' are for debug mode.

I updated the doc/install_win.md accordingly.

Best,
  Marc

**Comment by alex-seitz** [comment]
Hi Marc,

thank you, works great.

Best,
Alex
