### ISSUE TITLE
Warning "Virus genome path is missing from the settings" on GSvar start

### ISSUE THREAD

**Issue by alex-seitz** [imgag/ngs-bits#608]
Hi,
when starting GSvar, I geth the following Warning:
![grafik](https://github.com/user-attachments/assets/25a95b45-6529-43e4-b036-f104b2ffb6bb)

I'm guessing it relates to the igv_virus_genome (https://github.com/imgag/ngs-bits/blob/b0ee29638cf15d1780090c434fb2ba62dbcf860a/bin/GSvar.ini.example#L7C1-L7C22)

in the GSvar.ini. But I don't know what to put there or how to disable this error.
I don't want to distribute this version with this warning coming on every startup.
Can you please help me either set the correct value there or get rid of the error?

Thank you

**Comment by marc-sturm** [comment]
Hi Alex,

thanks for pointing us to the incomplete documentation there. 

The documentation of GSvar now contains information how to get the file:
https://github.com/imgag/ngs-bits/blob/master/doc/GSvar/configuration.md

Best,
  Marc

**Comment by alex-seitz** [comment]
Thank you
