### ISSUE TITLE
integrate RNA data into GSvar

### ISSUE THREAD

**Issue by marc-sturm** [imgag/ngs-bits#64]

**Comment by jakobmatthes** [comment]
megSAP:
- [ ] cohort relative/differential expression exon-level

ngs-bits:
- [ ] fix depth calculation in VariantAnnotateASE (spliced reads contribute to total depth)

GSvar main features:
- [ ] cohort expression widget (_expr.tsv)
- [ ] fusion widget (_fusions_arriba.tsv)

GSvar small features:
- [ ] open RNA tracks via GSvar
- [ ] fix queue analysis window for RNA samples
- [ ] GSvar: filter for RNA related columns
- [ ] circos plot: add significant ASE events as lines
- [ ] extra track: imprinting regions track

**Comment by leonschuetz** [comment]
RNA reference expression widget (table view for one file):
    - can have outdated info
    - viewer currently on file in sample folder

circos plot: add significant ASE events as lines:
    - criteria to decide what is significant

**Comment by leonschuetz** [comment]
- [ ] improve QC
    - [ ] calculate QC on housekeeping genes (?)
    

- [ ] improve docu

**Comment by leonschuetz** [comment]
- [ ] Import expression values into the NGSD
- [ ] Add ENSG ids to NGSD gene table
- [ ] Use exon region from the NGSD as target region? (UTR?)
- [ ] Compute expression statistics based on the NGSD (precomputed/on-the-fly?)

**Comment by leonschuetz** [comment]
- [ ] Import expression data of transcripts

**Comment by jakobmatthes** [comment]
- [ ] add "tissue" column for samples batch import in GSvar

**Comment by jakobmatthes** [comment]
- [ ] p-value from z-score: `p = 2 * normcdf(- abs(z))`, normcdf ist cumulative normal distribution function
- [ ] cohort strategies, show group field in expression window:
  - [ ] same processing, same tissue
  - [ ] same processing, same tissue, same project (interesting for research projects)
  - [ ] somatic: all samples with same HPO term **or** ICD10 code, also consider related ("same sample") DNA samples
- [ ] preselect transcript type protein_coding only
- [ ] implement tool to annotate variant lists with TPM/logFC/zscore/pval based on gene symbol

**Comment by leonschuetz** [comment]
- [ ] check sorting in ExpressionDataWidget

**Comment by leonschuetz** [comment]
#### positive controls:
RNA-205261 -> SCLT1, c.1294-2A>G und c.2005-1052_*363del
- splicing variant at chr4:128946154: leads to a het splicing variant (13bp)
- deletion of last exon 

RNA-2109460 -> SDCCAG8, c.740+267C>T und c.1946_1949del
- deletion of exons after variant (chr1:243305044), but coverage on other transcripts -> positive zscore

--> gene based approach in this cases not usefull, consider transcript base or exon based

**Comment by jakobmatthes** [comment]
- [ ] check sorting in ExpressionDataWidget (broken again?)
- [ ] improve default values/order/display

**Comment by leonschuetz** [comment]
- [ ] Add correlation check between RNA and DNA in somatic/germline pipeline

**Comment by leonschuetz** [comment]
Positive controls:

 - DX190880, GEMIN5, ENST00000285873.7, c.2523del, p.Lys842Argfs*10  -> reduzierte Expression
- DX2107906, NEU1, ENST00000375631.5, c.353-11A>G -> reduzierte Expression
- DX201301 , MARS1, ENST00000262027, c. 2100-1G>A -> Intron-Retention
- DX202057, TAB2, ENST00000637181.2, c.1764+1G>A -> aberrantes Spleißen, skipping Exon 4
