### ISSUE TITLE
NGSDImportHPO: Track source of term-gene relations

### ISSUE THREAD

**Issue by leonschuetz** [imgag/ngs-bits#66]
- store the gene-disease-phenotype relation and source (HPO, OMIM, HGMD...) instead of the gene-phenotype relatipon in the NGSD
- also add stringency to each relation  
- extend Phenotype filter in GSvar

**Comment by Ott-Alexander** [comment]
Was implemented in master with commit:
Final implementation of gene<>HPO relation import with source and evidence level details
 cbf5d8be51184563b20e1d6790db79ece73031d0
(Pull request #193 )
