### ISSUE TITLE
GSvar: Show genes in target region that overlap with a CNV/SV.

### ISSUE THREAD

**Issue by marc-sturm** [imgag/ngs-bits#78]
Implementation:
- Load gene list of target region (if exists)
- Convert genes to BedFile with ChromosomalIndex (use gene locus +-5000bp)
- On hover over gene column: show list of matching genes from target region "Target region gene overlap: XXX, YYY, ZZZ"

**Comment by leonschuetz** [comment]
Integrated in commit f8e14eceb65bcb06f775fd7d1aaeb0df8a535397
