### ISSUE TITLE
GSvar: electronic verison of "variant sheet"

### ISSUE THREAD

**Issue by marc-sturm** [imgag/ngs-bits#79]
Implement electronic version of variant sheet:
- add GSvar dialog for variant sheet:
  - pre-fill first time it is shown
  - if defined in NGSD, load from there
  - add flag "ACMG analyzed" to section ACMG and flag "Multi-Sample-Auswertung" to section "Filtering erfolgt"
  - remove name, birth date and barcode
- store results in NGSD table "diag_status_details"
  - delete with "diag_status" in ProcessedSampleDataDeletion
- generate document from from dialog
  - store as HTML (maybe RTF later)

**Comment by leonschuetz** [comment]
Implemented in 253926d8531986987083c5b16673a1b85023d5b3.

**Comment by leonschuetz** [comment]
Updated dialog and NGSD schema in d6cf08bde476263afa7ccc3e34d2a9bfac262131.

**Comment by marc-sturm** [comment]
@leonschuetz Special handling for trios is missing:
![grafik](https://user-images.githubusercontent.com/5638144/92209378-2cf0cf00-ee8d-11ea-9762-b2385cc21c8b.png)

**Comment by leonschuetz** [comment]
Fix in commit 1a3ac472f5526a84a3e3acea5a40ff9e886df867
