### ISSUE TITLE
when making build_tools_release, there is error. help!  

### ISSUE THREAD

**Issue by nordhuang** [imgag/ngs-bits#8]
../../src/cppNGS/VariantList.cpp:513:89: error: ‘class QList<QByteArray>’ has no member named ‘join’

**Comment by marc-sturm** [comment]
you probably use a too old Qt version.
Please check the output of 'qmake --version'.

Qt 5.5 or higher is required.

Best,
  Marc

**Comment by imgag** [comment]
Since there was no further feedback, I consider this issue solved.
