### ISSUE TITLE
Export essential somatic QC values to TSV

### ISSUE THREAD

**Issue by axelgschwind** [imgag/ngs-bits#87]
Somatic users need a button to export the most essential QCs of tumor and normal sample to a TSV table.

These include "is_tumor", "sample correlation", "somatic variant count", Q20%, Q30%, On-target region %, Duplicate read %, read depth, gender, Tumor content estimate.

**Comment by marc-sturm** [comment]
Why? What is the use case?

**Comment by axelgschwind** [comment]
Users of the somatic pipeline need to have a summary of QC of tumor-normal-pairs for their workflow.
Currently, they copy the overview of QC values from sample search and copy it to an error-prone excel sheet which generates this overview using Excel commands .

**Comment by axelgschwind** [comment]
Excel sheet will be adapted by users using "WVerweis" or "SVerweis"
